Unknown = ItemUpgrade(upgrade_id = -1,  name = "Unknown", upgrade_type = ItemUpgradeType.Unknown)
Icy_Axe = ItemUpgrade(upgrade_id = 0x0081,  name = "Icy", upgrade_type = ItemUpgradeType.Prefix)
Ebon_Axe = ItemUpgrade(upgrade_id = 0x0082,  name = "Ebon", upgrade_type = ItemUpgradeType.Prefix)
Shocking_Axe = ItemUpgrade(upgrade_id = 0x0083,  name = "Shocking", upgrade_type = ItemUpgradeType.Prefix)
Fiery_Axe = ItemUpgrade(upgrade_id = 0x0084,  name = "Fiery", upgrade_type = ItemUpgradeType.Prefix)
Barbed_Axe = ItemUpgrade(upgrade_id = 0x0092,  name = "Barbed", upgrade_type = ItemUpgradeType.Prefix)
Crippling_Axe = ItemUpgrade(upgrade_id = 0x0094,  name = "Crippling", upgrade_type = ItemUpgradeType.Prefix)
Cruel_Axe = ItemUpgrade(upgrade_id = 0x0096,  name = "Cruel", upgrade_type = ItemUpgradeType.Prefix)
Furious_Axe = ItemUpgrade(upgrade_id = 0x0099,  name = "Furious", upgrade_type = ItemUpgradeType.Prefix)
Poisonous_Axe = ItemUpgrade(upgrade_id = 0x009E,  name = "Poisonous", upgrade_type = ItemUpgradeType.Prefix)
Heavy_Axe = ItemUpgrade(upgrade_id = 0x00A1,  name = "Heavy", upgrade_type = ItemUpgradeType.Prefix)
Zealous_Axe = ItemUpgrade(upgrade_id = 0x00A3,  name = "Zealous", upgrade_type = ItemUpgradeType.Prefix)
Vampiric_Axe = ItemUpgrade(upgrade_id = 0x00A7,  name = "Vampiric", upgrade_type = ItemUpgradeType.Prefix)
Sundering_Axe = ItemUpgrade(upgrade_id = 0x00AB,  name = "Sundering", upgrade_type = ItemUpgradeType.Prefix)
OfDefense_Axe = ItemUpgrade(upgrade_id = 0x00C5,  name = "of Defense", upgrade_type = ItemUpgradeType.Suffix)
OfWarding_Axe = ItemUpgrade(upgrade_id = 0x00C7,  name = "of Warding", upgrade_type = ItemUpgradeType.Suffix)
OfShelter_Axe = ItemUpgrade(upgrade_id = 0x00CD,  name = "of Shelter", upgrade_type = ItemUpgradeType.Suffix)
OfSlaying_Axe = ItemUpgrade(upgrade_id = 0x00D4,  name = "of ____slaying", upgrade_type = ItemUpgradeType.Suffix)
OfFortitude_Axe = ItemUpgrade(upgrade_id = 0x00D9,  name = "of Fortitude", upgrade_type = ItemUpgradeType.Suffix)
OfEnchanting_Axe = ItemUpgrade(upgrade_id = 0x00DE,  name = "of Enchanting", upgrade_type = ItemUpgradeType.Suffix)
OfAxeMastery = ItemUpgrade(upgrade_id = 0x00E8,  name = "of Axe Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfTheProfession_Axe = ItemUpgrade(upgrade_id = 0x0226,  name = "of the Profession", upgrade_type = ItemUpgradeType.Suffix)
Icy_Bow = ItemUpgrade(upgrade_id = 0x0085,  name = "Icy", upgrade_type = ItemUpgradeType.Prefix)
Ebon_Bow = ItemUpgrade(upgrade_id = 0x0086,  name = "Ebon", upgrade_type = ItemUpgradeType.Prefix)
Shocking_Bow = ItemUpgrade(upgrade_id = 0x0087,  name = "Shocking", upgrade_type = ItemUpgradeType.Prefix)
Fiery_Bow = ItemUpgrade(upgrade_id = 0x0088,  name = "Fiery", upgrade_type = ItemUpgradeType.Prefix)
Poisonous_Bow = ItemUpgrade(upgrade_id = 0x009F,  name = "Poisonous", upgrade_type = ItemUpgradeType.Prefix)
Zealous_Bow = ItemUpgrade(upgrade_id = 0x00A5,  name = "Zealous", upgrade_type = ItemUpgradeType.Prefix)
Vampiric_Bow = ItemUpgrade(upgrade_id = 0x00A9,  name = "Vampiric", upgrade_type = ItemUpgradeType.Prefix)
Sundering_Bow = ItemUpgrade(upgrade_id = 0x00AD,  name = "Sundering", upgrade_type = ItemUpgradeType.Prefix)
OfDefense_Bow = ItemUpgrade(upgrade_id = 0x00C6,  name = "of Defense", upgrade_type = ItemUpgradeType.Suffix)
OfWarding_Bow = ItemUpgrade(upgrade_id = 0x00C8,  name = "of Warding", upgrade_type = ItemUpgradeType.Suffix)
OfShelter_Bow = ItemUpgrade(upgrade_id = 0x00CE,  name = "of Shelter", upgrade_type = ItemUpgradeType.Suffix)
OfSlaying_Bow = ItemUpgrade(upgrade_id = 0x00D5,  name = "of _____slaying", upgrade_type = ItemUpgradeType.Suffix)
OfFortitude_Bow = ItemUpgrade(upgrade_id = 0x00DA,  name = "of Fortitude", upgrade_type = ItemUpgradeType.Suffix)
OfEnchanting_Bow = ItemUpgrade(upgrade_id = 0x00DF,  name = "of Enchanting", upgrade_type = ItemUpgradeType.Suffix)
OfMarksmanship = ItemUpgrade(upgrade_id = 0x00E9,  name = "of Marksmanship", upgrade_type = ItemUpgradeType.Suffix)
Barbed_Bow = ItemUpgrade(upgrade_id = 0x0147,  name = "Barbed", upgrade_type = ItemUpgradeType.Prefix)
Crippling_Bow = ItemUpgrade(upgrade_id = 0x0148,  name = "Crippling", upgrade_type = ItemUpgradeType.Prefix)
Silencing_Bow = ItemUpgrade(upgrade_id = 0x0149,  name = "Silencing", upgrade_type = ItemUpgradeType.Prefix)
OfTheProfession_Bow = ItemUpgrade(upgrade_id = 0x0227,  name = "of the Profession", upgrade_type = ItemUpgradeType.Suffix)
Icy_Daggers = ItemUpgrade(upgrade_id = 0x012E,  name = "Icy", upgrade_type = ItemUpgradeType.Prefix)
Ebon_Daggers = ItemUpgrade(upgrade_id = 0x012F,  name = "Ebon", upgrade_type = ItemUpgradeType.Prefix)
Fiery_Daggers = ItemUpgrade(upgrade_id = 0x0130,  name = "Fiery", upgrade_type = ItemUpgradeType.Prefix)
Shocking_Daggers = ItemUpgrade(upgrade_id = 0x0131,  name = "Shocking", upgrade_type = ItemUpgradeType.Prefix)
Zealous_Daggers = ItemUpgrade(upgrade_id = 0x0132,  name = "Zealous", upgrade_type = ItemUpgradeType.Prefix)
Vampiric_Daggers = ItemUpgrade(upgrade_id = 0x0133,  name = "Vampiric", upgrade_type = ItemUpgradeType.Prefix)
Sundering_Daggers = ItemUpgrade(upgrade_id = 0x0134,  name = "Sundering", upgrade_type = ItemUpgradeType.Prefix)
Barbed_Daggers = ItemUpgrade(upgrade_id = 0x0135,  name = "Barbed", upgrade_type = ItemUpgradeType.Prefix)
Crippling_Daggers = ItemUpgrade(upgrade_id = 0x0136,  name = "Crippling", upgrade_type = ItemUpgradeType.Prefix)
Cruel_Daggers = ItemUpgrade(upgrade_id = 0x0137,  name = "Cruel", upgrade_type = ItemUpgradeType.Prefix)
Poisonous_Daggers = ItemUpgrade(upgrade_id = 0x0138,  name = "Poisonous", upgrade_type = ItemUpgradeType.Prefix)
Silencing_Daggers = ItemUpgrade(upgrade_id = 0x0139,  name = "Silencing", upgrade_type = ItemUpgradeType.Prefix)
Furious_Daggers = ItemUpgrade(upgrade_id = 0x013A,  name = "Furious", upgrade_type = ItemUpgradeType.Prefix)
OfDefense_Daggers = ItemUpgrade(upgrade_id = 0x0141,  name = "of Defense", upgrade_type = ItemUpgradeType.Suffix)
OfWarding_Daggers = ItemUpgrade(upgrade_id = 0x0142,  name = "of Warding", upgrade_type = ItemUpgradeType.Suffix)
OfShelter_Daggers = ItemUpgrade(upgrade_id = 0x0143,  name = "of Shelter", upgrade_type = ItemUpgradeType.Suffix)
OfEnchanting_Daggers = ItemUpgrade(upgrade_id = 0x0144,  name = "of Enchanting", upgrade_type = ItemUpgradeType.Suffix)
OfFortitude_Daggers = ItemUpgrade(upgrade_id = 0x0145,  name = "of Fortitude", upgrade_type = ItemUpgradeType.Suffix)
OfDaggerMastery = ItemUpgrade(upgrade_id = 0x0146,  name = "of Dagger Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfTheProfession_Daggers = ItemUpgrade(upgrade_id = 0x0228,  name = "of the Profession", upgrade_type = ItemUpgradeType.Suffix)
OfAptitude_Focus = ItemUpgrade(upgrade_id = 0x0217,  name = "of Aptitude", upgrade_type = ItemUpgradeType.Suffix)
OfFortitude_Focus = ItemUpgrade(upgrade_id = 0x0218,  name = "of Fortitude", upgrade_type = ItemUpgradeType.Suffix)
OfDevotion_Focus = ItemUpgrade(upgrade_id = 0x0219,  name = "of Devotion", upgrade_type = ItemUpgradeType.Suffix)
OfValor_Focus = ItemUpgrade(upgrade_id = 0x021A,  name = "of Valor", upgrade_type = ItemUpgradeType.Suffix)
OfEndurance_Focus = ItemUpgrade(upgrade_id = 0x021B,  name = "of Endurance", upgrade_type = ItemUpgradeType.Suffix)
OfSwiftness_Focus = ItemUpgrade(upgrade_id = 0x021C,  name = "of Swiftness", upgrade_type = ItemUpgradeType.Suffix)
Icy_Hammer = ItemUpgrade(upgrade_id = 0x0089,  name = "Icy", upgrade_type = ItemUpgradeType.Prefix)
Ebon_Hammer = ItemUpgrade(upgrade_id = 0x008A,  name = "Ebon", upgrade_type = ItemUpgradeType.Prefix)
Shocking_Hammer = ItemUpgrade(upgrade_id = 0x008B,  name = "Shocking", upgrade_type = ItemUpgradeType.Prefix)
Fiery_Hammer = ItemUpgrade(upgrade_id = 0x008C,  name = "Fiery", upgrade_type = ItemUpgradeType.Prefix)
Cruel_Hammer = ItemUpgrade(upgrade_id = 0x0097,  name = "Cruel", upgrade_type = ItemUpgradeType.Prefix)
Furious_Hammer = ItemUpgrade(upgrade_id = 0x009A,  name = "Furious", upgrade_type = ItemUpgradeType.Prefix)
Heavy_Hammer = ItemUpgrade(upgrade_id = 0x00A2,  name = "Heavy", upgrade_type = ItemUpgradeType.Prefix)
Zealous_Hammer = ItemUpgrade(upgrade_id = 0x00A4,  name = "Zealous", upgrade_type = ItemUpgradeType.Prefix)
Vampiric_Hammer = ItemUpgrade(upgrade_id = 0x00A8,  name = "Vampiric", upgrade_type = ItemUpgradeType.Prefix)
Sundering_Hammer = ItemUpgrade(upgrade_id = 0x00AC,  name = "Sundering", upgrade_type = ItemUpgradeType.Prefix)
OfWarding_Hammer = ItemUpgrade(upgrade_id = 0x00C9,  name = "of Warding", upgrade_type = ItemUpgradeType.Suffix)
OfDefense_Hammer = ItemUpgrade(upgrade_id = 0x00CC,  name = "of Defense", upgrade_type = ItemUpgradeType.Suffix)
OfShelter_Hammer = ItemUpgrade(upgrade_id = 0x00CF,  name = "of Shelter", upgrade_type = ItemUpgradeType.Suffix)
OfSlaying_Hammer = ItemUpgrade(upgrade_id = 0x00D6,  name = "of _____slaying", upgrade_type = ItemUpgradeType.Suffix)
OfFortitude_Hammer = ItemUpgrade(upgrade_id = 0x00DB,  name = "of Fortitude", upgrade_type = ItemUpgradeType.Suffix)
OfEnchanting_Hammer = ItemUpgrade(upgrade_id = 0x00E0,  name = "of Enchanting", upgrade_type = ItemUpgradeType.Suffix)
OfHammerMastery = ItemUpgrade(upgrade_id = 0x00EA,  name = "of Hammer Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfTheProfession_Hammer = ItemUpgrade(upgrade_id = 0x0229,  name = "of the Profession", upgrade_type = ItemUpgradeType.Suffix)
IHaveThePower = ItemUpgrade(upgrade_id = 0x015C,  name = "\"I have the power!\"", upgrade_type = ItemUpgradeType.Inscription)
LetTheMemoryLiveAgain = ItemUpgrade(upgrade_id = 0x015E,  name = "\"Let the Memory Live Again!\"", upgrade_type = ItemUpgradeType.Inscription)
TooMuchInformation = ItemUpgrade(upgrade_id = 0x0163,  name = "\"Too Much Information\"", upgrade_type = ItemUpgradeType.Inscription)
GuidedByFate = ItemUpgrade(upgrade_id = 0x0164,  name = "\"Guided by Fate\"", upgrade_type = ItemUpgradeType.Inscription)
StrengthAndHonor = ItemUpgrade(upgrade_id = 0x0165,  name = "\"Strength and Honor\"", upgrade_type = ItemUpgradeType.Inscription)
VengeanceIsMine = ItemUpgrade(upgrade_id = 0x0166,  name = "\"Vengeance is Mine\"", upgrade_type = ItemUpgradeType.Inscription)
DontFearTheReaper = ItemUpgrade(upgrade_id = 0x0167,  name = "\"Don't Fear the Reaper\"", upgrade_type = ItemUpgradeType.Inscription)
DanceWithDeath = ItemUpgrade(upgrade_id = 0x0168,  name = "\"Dance with Death\"", upgrade_type = ItemUpgradeType.Inscription)
BrawnOverBrains = ItemUpgrade(upgrade_id = 0x0169,  name = "\"Brawn over Brains\"", upgrade_type = ItemUpgradeType.Inscription)
ToThePain = ItemUpgrade(upgrade_id = 0x016A,  name = "\"To The Pain!\"", upgrade_type = ItemUpgradeType.Inscription)
IgnoranceIsBliss = ItemUpgrade(upgrade_id = 0x01B6,  name = "\"Ignorance is Bliss\"", upgrade_type = ItemUpgradeType.Inscription)
LifeIsPain = ItemUpgrade(upgrade_id = 0x01B7,  name = "\"Life is Pain\"", upgrade_type = ItemUpgradeType.Inscription)
ManForAllSeasons = ItemUpgrade(upgrade_id = 0x01B8,  name = "\"Man for All Seasons\"", upgrade_type = ItemUpgradeType.Inscription)
SurvivalOfTheFittest = ItemUpgrade(upgrade_id = 0x01B9,  name = "\"Survival of the Fittest\"", upgrade_type = ItemUpgradeType.Inscription)
MightMakesRight = ItemUpgrade(upgrade_id = 0x01BA,  name = "\"Might makes Right!\"", upgrade_type = ItemUpgradeType.Inscription)
KnowingIsHalfTheBattle = ItemUpgrade(upgrade_id = 0x01BB,  name = "\"Knowing is Half the Battle.\"", upgrade_type = ItemUpgradeType.Inscription)
FaithIsMy = ItemUpgrade(upgrade_id = 0x01BC,  name = "\"Faith is My \"", upgrade_type = ItemUpgradeType.Inscription)
DownButNotOut = ItemUpgrade(upgrade_id = 0x01BD,  name = "\"Down But Not Out\"", upgrade_type = ItemUpgradeType.Inscription)
HailToTheKing = ItemUpgrade(upgrade_id = 0x01BE,  name = "\"Hail to the King\"", upgrade_type = ItemUpgradeType.Inscription)
BeJustAndFearNot = ItemUpgrade(upgrade_id = 0x01BF,  name = "\"Be Just and Fear Not\"", upgrade_type = ItemUpgradeType.Inscription)
LiveForToday = ItemUpgrade(upgrade_id = 0x01C0,  name = "\"Live for Today\"", upgrade_type = ItemUpgradeType.Inscription)
SerenityNow = ItemUpgrade(upgrade_id = 0x01C1,  name = "\"Serenity Now\"", upgrade_type = ItemUpgradeType.Inscription)
ForgetMeNot = ItemUpgrade(upgrade_id = 0x01C2,  name = "\"Forget Me Not\"", upgrade_type = ItemUpgradeType.Inscription)
NotTheFace = ItemUpgrade(upgrade_id = 0x01C3,  name = "\"Not the face!\"", upgrade_type = ItemUpgradeType.Inscription)
LeafOnTheWind = ItemUpgrade(upgrade_id = 0x01C4,  name = "\"Leaf on the Wind\"", upgrade_type = ItemUpgradeType.Inscription)
LikeARollingStone = ItemUpgrade(upgrade_id = 0x01C5,  name = "\"Like a Rolling Stone\"", upgrade_type = ItemUpgradeType.Inscription)
RidersOnTheStorm = ItemUpgrade(upgrade_id = 0x01C6,  name = "\"Riders on the Storm\"", upgrade_type = ItemUpgradeType.Inscription)
SleepNowInTheFire = ItemUpgrade(upgrade_id = 0x01C7,  name = "\"Sleep Now in the Fire\"", upgrade_type = ItemUpgradeType.Inscription)
ThroughThickAndThin = ItemUpgrade(upgrade_id = 0x01C8,  name = "\"Through Thick and Thin\"", upgrade_type = ItemUpgradeType.Inscription)
TheRiddleOfSteel = ItemUpgrade(upgrade_id = 0x01C9,  name = "\"The Riddle of Steel\"", upgrade_type = ItemUpgradeType.Inscription)
FearCutsDeeper = ItemUpgrade(upgrade_id = 0x01CA,  name = "\"Fear Cuts Deeper\"", upgrade_type = ItemUpgradeType.Inscription)
ICanSeeClearlyNow = ItemUpgrade(upgrade_id = 0x01CB,  name = "\"I Can See Clearly Now\"", upgrade_type = ItemUpgradeType.Inscription)
SwiftAsTheWind = ItemUpgrade(upgrade_id = 0x01CC,  name = "\"Swift as the Wind\"", upgrade_type = ItemUpgradeType.Inscription)
StrengthOfBody = ItemUpgrade(upgrade_id = 0x01CD,  name = "\"Strength of Body\"", upgrade_type = ItemUpgradeType.Inscription)
CastOutTheUnclean = ItemUpgrade(upgrade_id = 0x01CE,  name = "\"Cast Out the Unclean\"", upgrade_type = ItemUpgradeType.Inscription)
PureOfHeart = ItemUpgrade(upgrade_id = 0x01CF,  name = "\"Pure of Heart\"", upgrade_type = ItemUpgradeType.Inscription)
SoundnessOfMind = ItemUpgrade(upgrade_id = 0x01D0,  name = "\"Soundness of Mind\"", upgrade_type = ItemUpgradeType.Inscription)
OnlyTheStrongSurvive = ItemUpgrade(upgrade_id = 0x01D1,  name = "\"Only the Strong Survive\"", upgrade_type = ItemUpgradeType.Inscription)
LuckOfTheDraw = ItemUpgrade(upgrade_id = 0x01D2,  name = "\"Luck of the Draw\"", upgrade_type = ItemUpgradeType.Inscription)
ShelteredByFaith = ItemUpgrade(upgrade_id = 0x01D3,  name = "\"Sheltered by Faith\"", upgrade_type = ItemUpgradeType.Inscription)
NothingToFear = ItemUpgrade(upgrade_id = 0x01D4,  name = "\"Nothing to Fear\"", upgrade_type = ItemUpgradeType.Inscription)
RunForYourLife = ItemUpgrade(upgrade_id = 0x01D5,  name = "\"Run For Your Life!\"", upgrade_type = ItemUpgradeType.Inscription)
MasterOfMyDomain = ItemUpgrade(upgrade_id = 0x01D6,  name = "\"Master of My Domain\"", upgrade_type = ItemUpgradeType.Inscription)
AptitudeNotAttitude = ItemUpgrade(upgrade_id = 0x01D7,  name = "\"Aptitude not Attitude\"", upgrade_type = ItemUpgradeType.Inscription)
SeizeTheDay = ItemUpgrade(upgrade_id = 0x01D8,  name = "\"Seize the Day\"", upgrade_type = ItemUpgradeType.Inscription)
HaveFaith = ItemUpgrade(upgrade_id = 0x01D9,  name = "\"Have Faith\"", upgrade_type = ItemUpgradeType.Inscription)
HaleAndHearty = ItemUpgrade(upgrade_id = 0x01DA,  name = "\"Hale and Hearty\"", upgrade_type = ItemUpgradeType.Inscription)
DontCallItAComeback = ItemUpgrade(upgrade_id = 0x01DB,  name = "\"Don't call it a comeback!\"", upgrade_type = ItemUpgradeType.Inscription)
IAmSorrow = ItemUpgrade(upgrade_id = 0x01DC,  name = "\"I am Sorrow.\"", upgrade_type = ItemUpgradeType.Inscription)
DontThinkTwice = ItemUpgrade(upgrade_id = 0x01DD,  name = "\"Don't Think Twice\"", upgrade_type = ItemUpgradeType.Inscription)
ShowMeTheMoney = ItemUpgrade(upgrade_id = 0x021E,  name = "\"Show me the money\"", upgrade_type = ItemUpgradeType.Inscription)
MeasureForMeasure = ItemUpgrade(upgrade_id = 0x021F,  name = "\"Measure for Measure\"", upgrade_type = ItemUpgradeType.Inscription)
Icy_Scythe = ItemUpgrade(upgrade_id = 0x016B,  name = "Icy", upgrade_type = ItemUpgradeType.Prefix)
Ebon_Scythe = ItemUpgrade(upgrade_id = 0x016C,  name = "Ebon", upgrade_type = ItemUpgradeType.Prefix)
Zealous_Scythe = ItemUpgrade(upgrade_id = 0x016F,  name = "Zealous", upgrade_type = ItemUpgradeType.Prefix)
Vampiric_Scythe = ItemUpgrade(upgrade_id = 0x0171,  name = "Vampiric", upgrade_type = ItemUpgradeType.Prefix)
Sundering_Scythe = ItemUpgrade(upgrade_id = 0x0173,  name = "Sundering", upgrade_type = ItemUpgradeType.Prefix)
Barbed_Scythe = ItemUpgrade(upgrade_id = 0x0174,  name = "Barbed", upgrade_type = ItemUpgradeType.Prefix)
Crippling_Scythe = ItemUpgrade(upgrade_id = 0x0175,  name = "Crippling", upgrade_type = ItemUpgradeType.Prefix)
Cruel_Scythe = ItemUpgrade(upgrade_id = 0x0176,  name = "Cruel", upgrade_type = ItemUpgradeType.Prefix)
Poisonous_Scythe = ItemUpgrade(upgrade_id = 0x0177,  name = "Poisonous", upgrade_type = ItemUpgradeType.Prefix)
Heavy_Scythe = ItemUpgrade(upgrade_id = 0x0178,  name = "Heavy", upgrade_type = ItemUpgradeType.Prefix)
Furious_Scythe = ItemUpgrade(upgrade_id = 0x0179,  name = "Furious", upgrade_type = ItemUpgradeType.Prefix)
OfDefense_Scythe = ItemUpgrade(upgrade_id = 0x0188,  name = "of Defense", upgrade_type = ItemUpgradeType.Suffix)
OfWarding_Scythe = ItemUpgrade(upgrade_id = 0x0189,  name = "of Warding", upgrade_type = ItemUpgradeType.Suffix)
OfShelter_Scythe = ItemUpgrade(upgrade_id = 0x018A,  name = "of Shelter", upgrade_type = ItemUpgradeType.Suffix)
OfEnchanting_Scythe = ItemUpgrade(upgrade_id = 0x018B,  name = "of Enchanting", upgrade_type = ItemUpgradeType.Suffix)
OfFortitude_Scythe = ItemUpgrade(upgrade_id = 0x018C,  name = "of Fortitude", upgrade_type = ItemUpgradeType.Suffix)
OfScytheMastery = ItemUpgrade(upgrade_id = 0x018D,  name = "of Scythe Mastery", upgrade_type = ItemUpgradeType.Suffix)
Fiery_Scythe = ItemUpgrade(upgrade_id = 0x020B,  name = "Fiery", upgrade_type = ItemUpgradeType.Prefix)
Shocking_Scythe = ItemUpgrade(upgrade_id = 0x020C,  name = "Shocking", upgrade_type = ItemUpgradeType.Prefix)
OfTheProfession_Scythe = ItemUpgrade(upgrade_id = 0x022C,  name = "of the Profession", upgrade_type = ItemUpgradeType.Suffix)
OfValor_Shield = ItemUpgrade(upgrade_id = 0x0151,  name = "of Valor", upgrade_type = ItemUpgradeType.Suffix)
OfEndurance_Shield = ItemUpgrade(upgrade_id = 0x0152,  name = "of Endurance", upgrade_type = ItemUpgradeType.Suffix)
OfFortitude_Shield = ItemUpgrade(upgrade_id = 0x0161,  name = "of Fortitude", upgrade_type = ItemUpgradeType.Suffix)
OfDevotion_Shield = ItemUpgrade(upgrade_id = 0x0162,  name = "of Devotion", upgrade_type = ItemUpgradeType.Suffix)
Fiery_Spear = ItemUpgrade(upgrade_id = 0x016D,  name = "Fiery", upgrade_type = ItemUpgradeType.Prefix)
Shocking_Spear = ItemUpgrade(upgrade_id = 0x016E,  name = "Shocking", upgrade_type = ItemUpgradeType.Prefix)
Zealous_Spear = ItemUpgrade(upgrade_id = 0x0170,  name = "Zealous", upgrade_type = ItemUpgradeType.Prefix)
Vampiric_Spear = ItemUpgrade(upgrade_id = 0x0172,  name = "Vampiric", upgrade_type = ItemUpgradeType.Prefix)
Sundering_Spear = ItemUpgrade(upgrade_id = 0x017A,  name = "Sundering", upgrade_type = ItemUpgradeType.Prefix)
Barbed_Spear = ItemUpgrade(upgrade_id = 0x017B,  name = "Barbed", upgrade_type = ItemUpgradeType.Prefix)
Crippling_Spear = ItemUpgrade(upgrade_id = 0x017C,  name = "Crippling", upgrade_type = ItemUpgradeType.Prefix)
Cruel_Spear = ItemUpgrade(upgrade_id = 0x017D,  name = "Cruel", upgrade_type = ItemUpgradeType.Prefix)
Poisonous_Spear = ItemUpgrade(upgrade_id = 0x017E,  name = "Poisonous", upgrade_type = ItemUpgradeType.Prefix)
Silencing_Spear = ItemUpgrade(upgrade_id = 0x017F,  name = "Silencing", upgrade_type = ItemUpgradeType.Prefix)
Furious_Spear = ItemUpgrade(upgrade_id = 0x0180,  name = "Furious", upgrade_type = ItemUpgradeType.Prefix)
Heavy_Spear = ItemUpgrade(upgrade_id = 0x0181,  name = "Heavy", upgrade_type = ItemUpgradeType.Prefix)
OfDefense_Spear = ItemUpgrade(upgrade_id = 0x018E,  name = "of Defense", upgrade_type = ItemUpgradeType.Suffix)
OfWarding_Spear = ItemUpgrade(upgrade_id = 0x018F,  name = "of Warding", upgrade_type = ItemUpgradeType.Suffix)
OfShelter_Spear = ItemUpgrade(upgrade_id = 0x0190,  name = "of Shelter", upgrade_type = ItemUpgradeType.Suffix)
OfEnchanting_Spear = ItemUpgrade(upgrade_id = 0x0191,  name = "of Enchanting", upgrade_type = ItemUpgradeType.Suffix)
OfFortitude_Spear = ItemUpgrade(upgrade_id = 0x0192,  name = "of Fortitude", upgrade_type = ItemUpgradeType.Suffix)
OfSpearMastery = ItemUpgrade(upgrade_id = 0x0193,  name = "of Spear Mastery", upgrade_type = ItemUpgradeType.Suffix)
Icy_Spear = ItemUpgrade(upgrade_id = 0x020D,  name = "Icy", upgrade_type = ItemUpgradeType.Prefix)
Ebon_Spear = ItemUpgrade(upgrade_id = 0x020E,  name = "Ebon", upgrade_type = ItemUpgradeType.Prefix)
OfTheProfession_Spear = ItemUpgrade(upgrade_id = 0x022D,  name = "of the Profession", upgrade_type = ItemUpgradeType.Suffix)
Defensive_Staff = ItemUpgrade(upgrade_id = 0x0091,  name = "Defensive", upgrade_type = ItemUpgradeType.Prefix)
Insightful_Staff = ItemUpgrade(upgrade_id = 0x009C,  name = "Insightful", upgrade_type = ItemUpgradeType.Prefix)
Hale_Staff = ItemUpgrade(upgrade_id = 0x009D,  name = "Hale", upgrade_type = ItemUpgradeType.Prefix)
OfAttribute_Staff = ItemUpgrade(upgrade_id = 0x00C3,  name = "of <Attribute>", upgrade_type = ItemUpgradeType.Suffix)
OfWarding_Staff = ItemUpgrade(upgrade_id = 0x00CA,  name = "of Warding", upgrade_type = ItemUpgradeType.Suffix)
OfShelter_Staff = ItemUpgrade(upgrade_id = 0x00D0,  name = "of Shelter", upgrade_type = ItemUpgradeType.Suffix)
OfDefense_Staff = ItemUpgrade(upgrade_id = 0x00D2,  name = "of Defense", upgrade_type = ItemUpgradeType.Suffix)
OfSlaying_Staff = ItemUpgrade(upgrade_id = 0x00D7,  name = "of _____slaying", upgrade_type = ItemUpgradeType.Suffix)
OfFortitude_Staff = ItemUpgrade(upgrade_id = 0x00DC,  name = "of Fortitude", upgrade_type = ItemUpgradeType.Suffix)
OfEnchanting_Staff = ItemUpgrade(upgrade_id = 0x00E1,  name = "of Enchanting", upgrade_type = ItemUpgradeType.Suffix)
OfMastery_Staff = ItemUpgrade(upgrade_id = 0x0153,  name = "of Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfDevotion_Staff = ItemUpgrade(upgrade_id = 0x0154,  name = "of Devotion", upgrade_type = ItemUpgradeType.Suffix)
OfValor_Staff = ItemUpgrade(upgrade_id = 0x0155,  name = "of Valor", upgrade_type = ItemUpgradeType.Suffix)
OfEndurance_Staff = ItemUpgrade(upgrade_id = 0x0156,  name = "of Endurance", upgrade_type = ItemUpgradeType.Suffix)
Swift_Staff = ItemUpgrade(upgrade_id = 0x020F,  name = "Swift", upgrade_type = ItemUpgradeType.Prefix)
Adept_Staff = ItemUpgrade(upgrade_id = 0x0210,  name = "Adept", upgrade_type = ItemUpgradeType.Prefix)
OfTheProfession_Staff = ItemUpgrade(upgrade_id = 0x022B,  name = "of the Profession", upgrade_type = ItemUpgradeType.Suffix)
Icy_Sword = ItemUpgrade(upgrade_id = 0x008D,  name = "Icy", upgrade_type = ItemUpgradeType.Prefix)
Ebon_Sword = ItemUpgrade(upgrade_id = 0x008E,  name = "Ebon", upgrade_type = ItemUpgradeType.Prefix)
Shocking_Sword = ItemUpgrade(upgrade_id = 0x008F,  name = "Shocking", upgrade_type = ItemUpgradeType.Prefix)
Fiery_Sword = ItemUpgrade(upgrade_id = 0x0090,  name = "Fiery", upgrade_type = ItemUpgradeType.Prefix)
Barbed_Sword = ItemUpgrade(upgrade_id = 0x0093,  name = "Barbed", upgrade_type = ItemUpgradeType.Prefix)
Crippling_Sword = ItemUpgrade(upgrade_id = 0x0095,  name = "Crippling", upgrade_type = ItemUpgradeType.Prefix)
Cruel_Sword = ItemUpgrade(upgrade_id = 0x0098,  name = "Cruel", upgrade_type = ItemUpgradeType.Prefix)
Furious_Sword = ItemUpgrade(upgrade_id = 0x009B,  name = "Furious", upgrade_type = ItemUpgradeType.Prefix)
Poisonous_Sword = ItemUpgrade(upgrade_id = 0x00A0,  name = "Poisonous", upgrade_type = ItemUpgradeType.Prefix)
Zealous_Sword = ItemUpgrade(upgrade_id = 0x00A6,  name = "Zealous", upgrade_type = ItemUpgradeType.Prefix)
Vampiric_Sword = ItemUpgrade(upgrade_id = 0x00AA,  name = "Vampiric", upgrade_type = ItemUpgradeType.Prefix)
Sundering_Sword = ItemUpgrade(upgrade_id = 0x00AE,  name = "Sundering", upgrade_type = ItemUpgradeType.Prefix)
OfWarding_Sword = ItemUpgrade(upgrade_id = 0x00CB,  name = "of Warding", upgrade_type = ItemUpgradeType.Suffix)
OfShelter_Sword = ItemUpgrade(upgrade_id = 0x00D1,  name = "of Shelter", upgrade_type = ItemUpgradeType.Suffix)
OfDefense_Sword = ItemUpgrade(upgrade_id = 0x00D3,  name = "of Defense", upgrade_type = ItemUpgradeType.Suffix)
OfSlaying_Sword = ItemUpgrade(upgrade_id = 0x00D8,  name = "of _____slaying", upgrade_type = ItemUpgradeType.Suffix)
OfFortitude_Sword = ItemUpgrade(upgrade_id = 0x00DD,  name = "of Fortitude", upgrade_type = ItemUpgradeType.Suffix)
OfEnchanting_Sword = ItemUpgrade(upgrade_id = 0x00E2,  name = "of Enchanting", upgrade_type = ItemUpgradeType.Suffix)
OfSwordsmanship = ItemUpgrade(upgrade_id = 0x00EB,  name = "of Swordsmanship", upgrade_type = ItemUpgradeType.Suffix)
OfTheProfession_Sword = ItemUpgrade(upgrade_id = 0x022E,  name = "of the Profession", upgrade_type = ItemUpgradeType.Suffix)
OfMemory_Wand = ItemUpgrade(upgrade_id = 0x015F,  name = "of Memory", upgrade_type = ItemUpgradeType.Suffix)
OfQuickening_Wand = ItemUpgrade(upgrade_id = 0x0160,  name = "of Quickening", upgrade_type = ItemUpgradeType.Suffix)
OfTheProfession_Wand = ItemUpgrade(upgrade_id = 0x022A,  name = "of the Profession", upgrade_type = ItemUpgradeType.Suffix)
Survivor = ItemUpgrade(upgrade_id = 0x01E6,  name = "Survivor", upgrade_type = ItemUpgradeType.Prefix)
Radiant = ItemUpgrade(upgrade_id = 0x01E5,  name = "Radiant", upgrade_type = ItemUpgradeType.Prefix)
Stalwart = ItemUpgrade(upgrade_id = 0x01E7,  name = "Stalwart", upgrade_type = ItemUpgradeType.Prefix)
Brawlers = ItemUpgrade(upgrade_id = 0x01E8,  name = "Brawler's", upgrade_type = ItemUpgradeType.Prefix)
Blessed = ItemUpgrade(upgrade_id = 0x01E9,  name = "Blessed", upgrade_type = ItemUpgradeType.Prefix)
Heralds = ItemUpgrade(upgrade_id = 0x01EA,  name = "Herald's", upgrade_type = ItemUpgradeType.Prefix)
Sentrys = ItemUpgrade(upgrade_id = 0x01EB,  name = "Sentry's", upgrade_type = ItemUpgradeType.Prefix)
Knights = ItemUpgrade(upgrade_id = 0x01F9,  name = "Knight's", upgrade_type = ItemUpgradeType.Prefix)
Lieutenants = ItemUpgrade(upgrade_id = 0x0208,  name = "Lieutenant's", upgrade_type = ItemUpgradeType.Prefix)
Stonefist = ItemUpgrade(upgrade_id = 0x0209,  name = "Stonefist", upgrade_type = ItemUpgradeType.Prefix)
Dreadnought = ItemUpgrade(upgrade_id = 0x01FA,  name = "Dreadnought", upgrade_type = ItemUpgradeType.Prefix)
Sentinels = ItemUpgrade(upgrade_id = 0x01FB,  name = "Sentinel's", upgrade_type = ItemUpgradeType.Prefix)
Frostbound = ItemUpgrade(upgrade_id = 0x01FC,  name = "Frostbound", upgrade_type = ItemUpgradeType.Prefix)
Pyrebound = ItemUpgrade(upgrade_id = 0x01FE,  name = "Pyrebound", upgrade_type = ItemUpgradeType.Prefix)
Stormbound = ItemUpgrade(upgrade_id = 0x01FF,  name = "Stormbound", upgrade_type = ItemUpgradeType.Prefix)
Scouts = ItemUpgrade(upgrade_id = 0x0201,  name = "Scout's", upgrade_type = ItemUpgradeType.Prefix)
Earthbound = ItemUpgrade(upgrade_id = 0x01FD,  name = "Earthbound", upgrade_type = ItemUpgradeType.Prefix)
Beastmasters = ItemUpgrade(upgrade_id = 0x0200,  name = "Beastmaster's", upgrade_type = ItemUpgradeType.Prefix)
Wanderers = ItemUpgrade(upgrade_id = 0x01F6,  name = "Wanderer's", upgrade_type = ItemUpgradeType.Prefix)
Disciples = ItemUpgrade(upgrade_id = 0x01F7,  name = "Disciple's", upgrade_type = ItemUpgradeType.Prefix)
Anchorites = ItemUpgrade(upgrade_id = 0x01F8,  name = "Anchorite's", upgrade_type = ItemUpgradeType.Prefix)
Bloodstained = ItemUpgrade(upgrade_id = 0x020A,  name = "Bloodstained", upgrade_type = ItemUpgradeType.Prefix)
Tormentors = ItemUpgrade(upgrade_id = 0x01EC,  name = "Tormentor's", upgrade_type = ItemUpgradeType.Prefix)
Bonelace = ItemUpgrade(upgrade_id = 0x01EE,  name = "Bonelace", upgrade_type = ItemUpgradeType.Prefix)
MinionMasters = ItemUpgrade(upgrade_id = 0x01EF,  name = "Minion Master's", upgrade_type = ItemUpgradeType.Prefix)
Blighters = ItemUpgrade(upgrade_id = 0x01F0,  name = "Blighter's", upgrade_type = ItemUpgradeType.Prefix)
Undertakers = ItemUpgrade(upgrade_id = 0x01ED,  name = "Undertaker's", upgrade_type = ItemUpgradeType.Prefix)
Virtuosos = ItemUpgrade(upgrade_id = 0x01E4,  name = "Virtuoso's", upgrade_type = ItemUpgradeType.Prefix)
Artificers = ItemUpgrade(upgrade_id = 0x01E2,  name = "Artificer's", upgrade_type = ItemUpgradeType.Prefix)
Prodigys = ItemUpgrade(upgrade_id = 0x01E3,  name = "Prodigy's", upgrade_type = ItemUpgradeType.Prefix)
Hydromancer = ItemUpgrade(upgrade_id = 0x01F2,  name = "Hydromancer", upgrade_type = ItemUpgradeType.Prefix)
Geomancer = ItemUpgrade(upgrade_id = 0x01F3,  name = "Geomancer", upgrade_type = ItemUpgradeType.Prefix)
Pyromancer = ItemUpgrade(upgrade_id = 0x01F4,  name = "Pyromancer", upgrade_type = ItemUpgradeType.Prefix)
Aeromancer = ItemUpgrade(upgrade_id = 0x01F5,  name = "Aeromancer", upgrade_type = ItemUpgradeType.Prefix)
Prismatic = ItemUpgrade(upgrade_id = 0x01F1,  name = "Prismatic", upgrade_type = ItemUpgradeType.Prefix)
Vanguards = ItemUpgrade(upgrade_id = 0x01DE,  name = "Vanguard's", upgrade_type = ItemUpgradeType.Prefix)
Infiltrators = ItemUpgrade(upgrade_id = 0x01DF,  name = "Infiltrator's", upgrade_type = ItemUpgradeType.Prefix)
Saboteurs = ItemUpgrade(upgrade_id = 0x01E0,  name = "Saboteur's", upgrade_type = ItemUpgradeType.Prefix)
Nightstalkers = ItemUpgrade(upgrade_id = 0x01E1,  name = "Nightstalker's", upgrade_type = ItemUpgradeType.Prefix)
Shamans = ItemUpgrade(upgrade_id = 0x0204,  name = "Shaman's", upgrade_type = ItemUpgradeType.Prefix)
GhostForge = ItemUpgrade(upgrade_id = 0x0205,  name = "Ghost Forge", upgrade_type = ItemUpgradeType.Prefix)
Mystics = ItemUpgrade(upgrade_id = 0x0206,  name = "Mystic's", upgrade_type = ItemUpgradeType.Prefix)
Windwalker = ItemUpgrade(upgrade_id = 0x0202,  name = "Windwalker", upgrade_type = ItemUpgradeType.Prefix)
Forsaken = ItemUpgrade(upgrade_id = 0x0203,  name = "Forsaken", upgrade_type = ItemUpgradeType.Prefix)
Centurions = ItemUpgrade(upgrade_id = 0x0207,  name = "Centurion's", upgrade_type = ItemUpgradeType.Prefix)
OfAttunement = ItemUpgrade(upgrade_id = 0x0211,  name = "of Attunement", upgrade_type = ItemUpgradeType.Suffix)
OfRecovery = ItemUpgrade(upgrade_id = 0x0213,  name = "of Recovery", upgrade_type = ItemUpgradeType.Suffix)
OfRestoration = ItemUpgrade(upgrade_id = 0x0214,  name = "of Restoration", upgrade_type = ItemUpgradeType.Suffix)
OfClarity = ItemUpgrade(upgrade_id = 0x0215,  name = "of Clarity", upgrade_type = ItemUpgradeType.Suffix)
OfPurity = ItemUpgrade(upgrade_id = 0x0216,  name = "of Purity", upgrade_type = ItemUpgradeType.Suffix)
OfMinorVigor = ItemUpgrade(upgrade_id = 0x00FF,  name = "of Minor Vigor", upgrade_type = ItemUpgradeType.Suffix)
OfMinorVigor2 = ItemUpgrade(upgrade_id = 0x00C2,  name = "of Minor Vigor", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorVigor = ItemUpgrade(upgrade_id = 0x0101,  name = "of Superior Vigor", upgrade_type = ItemUpgradeType.Suffix)
OfMajorVigor = ItemUpgrade(upgrade_id = 0x0100,  name = "of Major Vigor", upgrade_type = ItemUpgradeType.Suffix)
OfVitae = ItemUpgrade(upgrade_id = 0x0212,  name = "of Vitae", upgrade_type = ItemUpgradeType.Suffix)
OfMinorAbsorption = ItemUpgrade(upgrade_id = 0x00FC,  name = "of Minor Absorption", upgrade_type = ItemUpgradeType.Suffix)
OfMinorTactics = ItemUpgrade(upgrade_id = 0x1501,  name = "of Minor Tactics", upgrade_type = ItemUpgradeType.Suffix)
OfMinorStrength = ItemUpgrade(upgrade_id = 0x1101,  name = "of Minor Strength", upgrade_type = ItemUpgradeType.Suffix)
OfMinorAxeMastery = ItemUpgrade(upgrade_id = 0x1201,  name = "of Minor Axe Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfMinorHammerMastery = ItemUpgrade(upgrade_id = 0x1301,  name = "of Minor Hammer Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfMinorSwordsmanship = ItemUpgrade(upgrade_id = 0x1401,  name = "of Minor Swordsmanship", upgrade_type = ItemUpgradeType.Suffix)
OfMajorAbsorption = ItemUpgrade(upgrade_id = 0x00FD,  name = "of Major Absorption", upgrade_type = ItemUpgradeType.Suffix)
OfMajorTactics = ItemUpgrade(upgrade_id = 0x1502,  name = "of Major Tactics", upgrade_type = ItemUpgradeType.Suffix)
OfMajorStrength = ItemUpgrade(upgrade_id = 0x1102,  name = "of Major Strength", upgrade_type = ItemUpgradeType.Suffix)
OfMajorAxeMastery = ItemUpgrade(upgrade_id = 0x1202,  name = "of Major Axe Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfMajorHammerMastery = ItemUpgrade(upgrade_id = 0x1302,  name = "of Major Hammer Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfMajorSwordsmanship = ItemUpgrade(upgrade_id = 0x1402,  name = "of Major Swordsmanship", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorAbsorption = ItemUpgrade(upgrade_id = 0x00FE,  name = "of Superior Absorption", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorTactics = ItemUpgrade(upgrade_id = 0x1503,  name = "of Superior Tactics", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorStrength = ItemUpgrade(upgrade_id = 0x1103,  name = "of Superior Strength", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorAxeMastery = ItemUpgrade(upgrade_id = 0x1203,  name = "of Superior Axe Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorHammerMastery = ItemUpgrade(upgrade_id = 0x1303,  name = "of Superior Hammer Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorSwordsmanship = ItemUpgrade(upgrade_id = 0x1403,  name = "of Superior Swordsmanship", upgrade_type = ItemUpgradeType.Suffix)
OfMinorWildernessSurvival = ItemUpgrade(upgrade_id = 0x1801,  name = "of Minor Wilderness Survival", upgrade_type = ItemUpgradeType.Suffix)
OfMinorExpertise = ItemUpgrade(upgrade_id = 0x1701,  name = "of Minor Expertise", upgrade_type = ItemUpgradeType.Suffix)
OfMinorBeastMastery = ItemUpgrade(upgrade_id = 0x1601,  name = "of Minor Beast Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfMinorMarksmanship = ItemUpgrade(upgrade_id = 0x1901,  name = "of Minor Marksmanship", upgrade_type = ItemUpgradeType.Suffix)
OfMajorWildernessSurvival = ItemUpgrade(upgrade_id = 0x1802,  name = "of Major Wilderness Survival", upgrade_type = ItemUpgradeType.Suffix)
OfMajorExpertise = ItemUpgrade(upgrade_id = 0x1702,  name = "of Major Expertise", upgrade_type = ItemUpgradeType.Suffix)
OfMajorBeastMastery = ItemUpgrade(upgrade_id = 0x1602,  name = "of Major Beast Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfMajorMarksmanship = ItemUpgrade(upgrade_id = 0x1902,  name = "of Major Marksmanship", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorWildernessSurvival = ItemUpgrade(upgrade_id = 0x1803,  name = "of Superior Wilderness Survival", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorExpertise = ItemUpgrade(upgrade_id = 0x1703,  name = "of Superior Expertise", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorBeastMastery = ItemUpgrade(upgrade_id = 0x1603,  name = "of Superior Beast Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorMarksmanship = ItemUpgrade(upgrade_id = 0x1903,  name = "of Superior Marksmanship", upgrade_type = ItemUpgradeType.Suffix)
OfMinorHealingPrayers = ItemUpgrade(upgrade_id = 0x0D01,  name = "of Minor Healing Prayers", upgrade_type = ItemUpgradeType.Suffix)
OfMinorSmitingPrayers = ItemUpgrade(upgrade_id = 0x0E01,  name = "of Minor Smiting Prayers", upgrade_type = ItemUpgradeType.Suffix)
OfMinorProtectionPrayers = ItemUpgrade(upgrade_id = 0x0F01,  name = "of Minor Protection Prayers", upgrade_type = ItemUpgradeType.Suffix)
OfMinorDivineFavor = ItemUpgrade(upgrade_id = 0x1001,  name = "of Minor Divine Favor", upgrade_type = ItemUpgradeType.Suffix)
OfMajorHealingPrayers = ItemUpgrade(upgrade_id = 0x0D02,  name = "of Major Healing Prayers", upgrade_type = ItemUpgradeType.Suffix)
OfMajorSmitingPrayers = ItemUpgrade(upgrade_id = 0x0E02,  name = "of Major Smiting Prayers", upgrade_type = ItemUpgradeType.Suffix)
OfMajorProtectionPrayers = ItemUpgrade(upgrade_id = 0x0F02,  name = "of Major Protection Prayers", upgrade_type = ItemUpgradeType.Suffix)
OfMajorDivineFavor = ItemUpgrade(upgrade_id = 0x1002,  name = "of Major Divine Favor", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorHealingPrayers = ItemUpgrade(upgrade_id = 0x0D03,  name = "of Superior Healing Prayers", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorSmitingPrayers = ItemUpgrade(upgrade_id = 0x0E03,  name = "of Superior Smiting Prayers", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorProtectionPrayers = ItemUpgrade(upgrade_id = 0x0F03,  name = "of Superior Protection Prayers", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorDivineFavor = ItemUpgrade(upgrade_id = 0x1003,  name = "of Superior Divine Favor", upgrade_type = ItemUpgradeType.Suffix)
OfMinorBloodMagic = ItemUpgrade(upgrade_id = 0x0401,  name = "of Minor Blood Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMinorDeathMagic = ItemUpgrade(upgrade_id = 0x0501,  name = "of Minor Death Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMinorCurses = ItemUpgrade(upgrade_id = 0x0701,  name = "of Minor Curses", upgrade_type = ItemUpgradeType.Suffix)
OfMinorSoulReaping = ItemUpgrade(upgrade_id = 0x0601,  name = "of Minor Soul Reaping", upgrade_type = ItemUpgradeType.Suffix)
OfMajorBloodMagic = ItemUpgrade(upgrade_id = 0x0402,  name = "of Major Blood Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMajorDeathMagic = ItemUpgrade(upgrade_id = 0x0502,  name = "of Major Death Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMajorCurses = ItemUpgrade(upgrade_id = 0x0702,  name = "of Major Curses", upgrade_type = ItemUpgradeType.Suffix)
OfMajorSoulReaping = ItemUpgrade(upgrade_id = 0x0602,  name = "of Major Soul Reaping", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorBloodMagic = ItemUpgrade(upgrade_id = 0x0403,  name = "of Superior Blood Magic", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorDeathMagic = ItemUpgrade(upgrade_id = 0x0503,  name = "of Superior Death Magic", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorCurses = ItemUpgrade(upgrade_id = 0x0703,  name = "of Superior Curses", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorSoulReaping = ItemUpgrade(upgrade_id = 0x0603,  name = "of Superior Soul Reaping", upgrade_type = ItemUpgradeType.Suffix)
OfMinorFastCasting = ItemUpgrade(upgrade_id = 0x0001,  name = "of Minor Fast Casting", upgrade_type = ItemUpgradeType.Suffix)
OfMinorDominationMagic = ItemUpgrade(upgrade_id = 0x0201,  name = "of Minor Domination Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMinorIllusionMagic = ItemUpgrade(upgrade_id = 0x0101,  name = "of Minor Illusion Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMinorInspirationMagic = ItemUpgrade(upgrade_id = 0x0301,  name = "of Minor Inspiration Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMajorFastCasting = ItemUpgrade(upgrade_id = 0x0002,  name = "of Major Fast Casting", upgrade_type = ItemUpgradeType.Suffix)
OfMajorDominationMagic = ItemUpgrade(upgrade_id = 0x0202,  name = "of Major Domination Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMajorIllusionMagic = ItemUpgrade(upgrade_id = 0x0102,  name = "of Major Illusion Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMajorInspirationMagic = ItemUpgrade(upgrade_id = 0x0302,  name = "of Major Inspiration Magic", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorFastCasting = ItemUpgrade(upgrade_id = 0x0003,  name = "of Superior Fast Casting", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorDominationMagic = ItemUpgrade(upgrade_id = 0x0203,  name = "of Superior Domination Magic", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorIllusionMagic = ItemUpgrade(upgrade_id = 0x0103,  name = "of Superior Illusion Magic", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorInspirationMagic = ItemUpgrade(upgrade_id = 0x0303,  name = "of Superior Inspiration Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMinorEnergyStorage = ItemUpgrade(upgrade_id = 0x0C01,  name = "of Minor Energy Storage", upgrade_type = ItemUpgradeType.Suffix)
OfMinorFireMagic = ItemUpgrade(upgrade_id = 0x0A01,  name = "of Minor Fire Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMinorAirMagic = ItemUpgrade(upgrade_id = 0x0801,  name = "of Minor Air Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMinorEarthMagic = ItemUpgrade(upgrade_id = 0x0901,  name = "of Minor Earth Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMinorWaterMagic = ItemUpgrade(upgrade_id = 0x0B01,  name = "of Minor Water Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMajorEnergyStorage = ItemUpgrade(upgrade_id = 0x0C02,  name = "of Major Energy Storage", upgrade_type = ItemUpgradeType.Suffix)
OfMajorFireMagic = ItemUpgrade(upgrade_id = 0x0A02,  name = "of Major Fire Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMajorAirMagic = ItemUpgrade(upgrade_id = 0x0802,  name = "of Major Air Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMajorEarthMagic = ItemUpgrade(upgrade_id = 0x0902,  name = "of Major Earth Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMajorWaterMagic = ItemUpgrade(upgrade_id = 0x0B02,  name = "of Major Water Magic", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorEnergyStorage = ItemUpgrade(upgrade_id = 0x0C03,  name = "of Superior Energy Storage", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorFireMagic = ItemUpgrade(upgrade_id = 0x0A03,  name = "of Superior Fire Magic", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorAirMagic = ItemUpgrade(upgrade_id = 0x0803,  name = "of Superior Air Magic", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorEarthMagic = ItemUpgrade(upgrade_id = 0x0903,  name = "of Superior Earth Magic", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorWaterMagic = ItemUpgrade(upgrade_id = 0x0B03,  name = "of Superior Water Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMinorCriticalStrikes = ItemUpgrade(upgrade_id = 0x2301,  name = "of Minor Critical Strikes", upgrade_type = ItemUpgradeType.Suffix)
OfMinorDaggerMastery = ItemUpgrade(upgrade_id = 0x1D01,  name = "of Minor Dagger Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfMinorDeadlyArts = ItemUpgrade(upgrade_id = 0x1E01,  name = "of Minor Deadly Arts", upgrade_type = ItemUpgradeType.Suffix)
OfMinorShadowArts = ItemUpgrade(upgrade_id = 0x1F01,  name = "of Minor Shadow Arts", upgrade_type = ItemUpgradeType.Suffix)
OfMajorCriticalStrikes = ItemUpgrade(upgrade_id = 0x2302,  name = "of Major Critical Strikes", upgrade_type = ItemUpgradeType.Suffix)
OfMajorDaggerMastery = ItemUpgrade(upgrade_id = 0x1D02,  name = "of Major Dagger Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfMajorDeadlyArts = ItemUpgrade(upgrade_id = 0x1E02,  name = "of Major Deadly Arts", upgrade_type = ItemUpgradeType.Suffix)
OfMajorShadowArts = ItemUpgrade(upgrade_id = 0x1F02,  name = "of Major Shadow Arts", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorCriticalStrikes = ItemUpgrade(upgrade_id = 0x2303,  name = "of Superior Critical Strikes", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorDaggerMastery = ItemUpgrade(upgrade_id = 0x1D03,  name = "of Superior Dagger Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorDeadlyArts = ItemUpgrade(upgrade_id = 0x1E03,  name = "of Superior Deadly Arts", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorShadowArts = ItemUpgrade(upgrade_id = 0x1F03,  name = "of Superior Shadow Arts", upgrade_type = ItemUpgradeType.Suffix)
OfMinorChannelingMagic = ItemUpgrade(upgrade_id = 0x2201,  name = "of Minor Channeling Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMinorRestorationMagic = ItemUpgrade(upgrade_id = 0x2101,  name = "of Minor Restoration Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMinorCommuning = ItemUpgrade(upgrade_id = 0x2001,  name = "of Minor Communing", upgrade_type = ItemUpgradeType.Suffix)
OfMinorSpawningPower = ItemUpgrade(upgrade_id = 0x2401,  name = "of Minor Spawning Power", upgrade_type = ItemUpgradeType.Suffix)
OfMajorChannelingMagic = ItemUpgrade(upgrade_id = 0x2202,  name = "of Major Channeling Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMajorRestorationMagic = ItemUpgrade(upgrade_id = 0x2102,  name = "of Major Restoration Magic", upgrade_type = ItemUpgradeType.Suffix)
OfMajorCommuning = ItemUpgrade(upgrade_id = 0x2002,  name = "of Major Communing", upgrade_type = ItemUpgradeType.Suffix)
OfMajorSpawningPower = ItemUpgrade(upgrade_id = 0x2402,  name = "of Major Spawning Power", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorChannelingMagic = ItemUpgrade(upgrade_id = 0x2203,  name = "of Superior Channeling Magic", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorRestorationMagic = ItemUpgrade(upgrade_id = 0x2103,  name = "of Superior Restoration Magic", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorCommuning = ItemUpgrade(upgrade_id = 0x2003,  name = "of Superior Communing", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorSpawningPower = ItemUpgrade(upgrade_id = 0x2403,  name = "of Superior Spawning Power", upgrade_type = ItemUpgradeType.Suffix)
OfMinorMysticism = ItemUpgrade(upgrade_id = 0x2C01,  name = "of Minor Mysticism", upgrade_type = ItemUpgradeType.Suffix)
OfMinorEarthPrayers = ItemUpgrade(upgrade_id = 0x2B01,  name = "of Minor Earth Prayers", upgrade_type = ItemUpgradeType.Suffix)
OfMinorScytheMastery = ItemUpgrade(upgrade_id = 0x2901,  name = "of Minor Scythe Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfMinorWindPrayers = ItemUpgrade(upgrade_id = 0x2A01,  name = "of Minor Wind Prayers", upgrade_type = ItemUpgradeType.Suffix)
OfMajorMysticism = ItemUpgrade(upgrade_id = 0x2C02,  name = "of Major Mysticism", upgrade_type = ItemUpgradeType.Suffix)
OfMajorEarthPrayers = ItemUpgrade(upgrade_id = 0x2B02,  name = "of Major Earth Prayers", upgrade_type = ItemUpgradeType.Suffix)
OfMajorScytheMastery = ItemUpgrade(upgrade_id = 0x2902,  name = "of Major Scythe Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfMajorWindPrayers = ItemUpgrade(upgrade_id = 0x2A02,  name = "of Major Wind Prayers", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorMysticism = ItemUpgrade(upgrade_id = 0x2C03,  name = "of Superior Mysticism", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorEarthPrayers = ItemUpgrade(upgrade_id = 0x2B03,  name = "of Superior Earth Prayers", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorScytheMastery = ItemUpgrade(upgrade_id = 0x2903,  name = "of Superior Scythe Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorWindPrayers = ItemUpgrade(upgrade_id = 0x2A03,  name = "of Superior Wind Prayers", upgrade_type = ItemUpgradeType.Suffix)
OfMinorLeadership = ItemUpgrade(upgrade_id = 0x2801,  name = "of Minor Leadership", upgrade_type = ItemUpgradeType.Suffix)
OfMinorMotivation = ItemUpgrade(upgrade_id = 0x2701,  name = "of Minor Motivation", upgrade_type = ItemUpgradeType.Suffix)
OfMinorCommand = ItemUpgrade(upgrade_id = 0x2601,  name = "of Minor Command", upgrade_type = ItemUpgradeType.Suffix)
OfMinorSpearMastery = ItemUpgrade(upgrade_id = 0x2501,  name = "of Minor Spear Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfMajorLeadership = ItemUpgrade(upgrade_id = 0x2802,  name = "of Major Leadership", upgrade_type = ItemUpgradeType.Suffix)
OfMajorMotivation = ItemUpgrade(upgrade_id = 0x2702,  name = "of Major Motivation", upgrade_type = ItemUpgradeType.Suffix)
OfMajorCommand = ItemUpgrade(upgrade_id = 0x2602,  name = "of Major Command", upgrade_type = ItemUpgradeType.Suffix)
OfMajorSpearMastery = ItemUpgrade(upgrade_id = 0x2502,  name = "of Major Spear Mastery", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorLeadership = ItemUpgrade(upgrade_id = 0x2803,  name = "of Superior Leadership", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorMotivation = ItemUpgrade(upgrade_id = 0x2703,  name = "of Superior Motivation", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorCommand = ItemUpgrade(upgrade_id = 0x2603,  name = "of Superior Command", upgrade_type = ItemUpgradeType.Suffix)
OfSuperiorSpearMastery = ItemUpgrade(upgrade_id = 0x2503,  name = "of Superior Spear Mastery", upgrade_type = ItemUpgradeType.Suffix)
UpgradeMinorRune_Warrior = ItemUpgrade(upgrade_id = 0x00B3,  name = "Upgrade warrior minor rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMinorRune_Warrior = ItemUpgrade(upgrade_id = 0x0167,  name = "Applies to warrior minor rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMajorRune_Warrior = ItemUpgrade(upgrade_id = 0x00B9,  name = "Upgrade warrior major rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMajorRune_Warrior = ItemUpgrade(upgrade_id = 0x0173,  name = "Applies to warrior major rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeSuperiorRune_Warrior = ItemUpgrade(upgrade_id = 0x00BF,  name = "Upgrade warrior superior rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToSuperiorRune_Warrior = ItemUpgrade(upgrade_id = 0x017F,  name = "Applies to warrior superior rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMinorRune_Ranger = ItemUpgrade(upgrade_id = 0x00B4,  name = "Upgrade ranger minor rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMinorRune_Ranger = ItemUpgrade(upgrade_id = 0x0169,  name = "Applies to ranger minor rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMajorRune_Ranger = ItemUpgrade(upgrade_id = 0x00BA,  name = "Upgrade ranger major rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMajorRune_Ranger = ItemUpgrade(upgrade_id = 0x0175,  name = "Applies to ranger major rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeSuperiorRune_Ranger = ItemUpgrade(upgrade_id = 0x00C0,  name = "Upgrade ranger superior rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToSuperiorRune_Ranger = ItemUpgrade(upgrade_id = 0x0181,  name = "Applies to ranger superior rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMinorRune_Monk = ItemUpgrade(upgrade_id = 0x00B2,  name = "Upgrade monk major rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMinorRune_Monk = ItemUpgrade(upgrade_id = 0x0165,  name = "Applies to monk minor rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMajorRune_Monk = ItemUpgrade(upgrade_id = 0x00B8,  name = "Upgrade monk major rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMajorRune_Monk = ItemUpgrade(upgrade_id = 0x0171,  name = "Applies to monk major rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeSuperiorRune_Monk = ItemUpgrade(upgrade_id = 0x00BE,  name = "Upgrade monk superior rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToSuperiorRune_Monk = ItemUpgrade(upgrade_id = 0x017D,  name = "Applies to monk superior rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMinorRune_Necromancer = ItemUpgrade(upgrade_id = 0x00B0,  name = "Upgrade necromancer minor rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMinorRune_Necromancer = ItemUpgrade(upgrade_id = 0x0161,  name = "Applies to necromancer minor rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMajorRune_Necromancer = ItemUpgrade(upgrade_id = 0x00B6,  name = "Upgrade necromancer major rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMajorRune_Necromancer = ItemUpgrade(upgrade_id = 0x016D,  name = "Applies to necromancer major rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeSuperiorRune_Necromancer = ItemUpgrade(upgrade_id = 0x00BC,  name = "Upgrade necromancer superior rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToSuperiorRune_Necromancer = ItemUpgrade(upgrade_id = 0x0179,  name = "Applies to necromancer superior rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMinorRune_Mesmer = ItemUpgrade(upgrade_id = 0x00AF,  name = "Upgrade mesmer minor rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMinorRune_Mesmer = ItemUpgrade(upgrade_id = 0x015F,  name = "Applies to mesmer minor rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMajorRune_Mesmer = ItemUpgrade(upgrade_id = 0x00B5,  name = "Upgrade mesmer major rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMajorRune_Mesmer = ItemUpgrade(upgrade_id = 0x016B,  name = "Applies to mesmer major rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeSuperiorRune_Mesmer = ItemUpgrade(upgrade_id = 0x00BB,  name = "Upgrade mesmer superior rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToSuperiorRune_Mesmer = ItemUpgrade(upgrade_id = 0x0177,  name = "Applies to mesmer superior rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMinorRune_Elementalist = ItemUpgrade(upgrade_id = 0x00B1,  name = "Upgrade elementalist minor rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMinorRune_Elementalist = ItemUpgrade(upgrade_id = 0x0163,  name = "Applies to elementalist minor rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMajorRune_Elementalist = ItemUpgrade(upgrade_id = 0x00B7,  name = "Upgrade elementalist major rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMajorRune_Elementalist = ItemUpgrade(upgrade_id = 0x016F,  name = "Applies to elementalist major rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeSuperiorRune_Elementalist = ItemUpgrade(upgrade_id = 0x00BD,  name = "Upgrade elementalist superior rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToSuperiorRune_Elementalist = ItemUpgrade(upgrade_id = 0x017B,  name = "Applies to elementalist superior rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMinorRune_Assassin = ItemUpgrade(upgrade_id = 0x013B,  name = "Upgrade assassin minor rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMinorRune_Assassin = ItemUpgrade(upgrade_id = 0x0277,  name = "Applies to assassin minor rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMajorRune_Assassin = ItemUpgrade(upgrade_id = 0x014C,  name = "Upgrade assassin major rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMajorRune_Assassin = ItemUpgrade(upgrade_id = 0x0279,  name = "Applies to assassin major rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeSuperiorRune_Assassin = ItemUpgrade(upgrade_id = 0x013D,  name = "Upgrade assassin superior rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToSuperiorRune_Assassin = ItemUpgrade(upgrade_id = 0x027B,  name = "Applies to assassin superior rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMinorRune_Ritualist = ItemUpgrade(upgrade_id = 0x013E,  name = "Upgrade ritualist minor rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMinorRune_Ritualist = ItemUpgrade(upgrade_id = 0x027D,  name = "Applies to ritualist minor rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMajorRune_Ritualist = ItemUpgrade(upgrade_id = 0x013F,  name = "Upgrade ritualist major rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMajorRune_Ritualist = ItemUpgrade(upgrade_id = 0x027F,  name = "Applies to ritualist major rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeSuperiorRune_Ritualist = ItemUpgrade(upgrade_id = 0x0140,  name = "Upgrade ritualist superior rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToSuperiorRune_Ritualist = ItemUpgrade(upgrade_id = 0x0281,  name = "Applies to ritualist superior rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMinorRune_Dervish = ItemUpgrade(upgrade_id = 0x0182,  name = "Upgrade dervish minor rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMinorRune_Dervish = ItemUpgrade(upgrade_id = 0x0305,  name = "Applies to dervish minor rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMajorRune_Dervish = ItemUpgrade(upgrade_id = 0x0183,  name = "Upgrade dervish major rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMajorRune_Dervish = ItemUpgrade(upgrade_id = 0x0307,  name = "Applies to dervish major rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeSuperiorRune_Dervish = ItemUpgrade(upgrade_id = 0x0184,  name = "Upgrade dervish superior rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToSuperiorRune_Dervish = ItemUpgrade(upgrade_id = 0x0309,  name = "Applies to dervish superior rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMinorRune_Paragon = ItemUpgrade(upgrade_id = 0x0185,  name = "Upgrade paragon minor rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMinorRune_Paragon = ItemUpgrade(upgrade_id = 0x030B,  name = "Applies to paragon minor rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeMajorRune_Paragon = ItemUpgrade(upgrade_id = 0x0186,  name = "Upgrade paragon major rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToMajorRune_Paragon = ItemUpgrade(upgrade_id = 0x030D,  name = "Applies to paragon major rune", upgrade_type = ItemUpgradeType.AppliesToRune)
UpgradeSuperiorRune_Paragon = ItemUpgrade(upgrade_id = 0x0187,  name = "Upgrade paragon superior rune", upgrade_type = ItemUpgradeType.UpgradeRune)
AppliesToSuperiorRune_Paragon = ItemUpgrade(upgrade_id = 0x030F,  name = "Applies to paragon superior rune", upgrade_type = ItemUpgradeType.AppliesToRune)
