from dataclasses import dataclass
from enum import Enum, IntEnum
from typing import Optional
from typing import Optional

from Py4GWCoreLib.UIManager import UIManager
from Py4GWCoreLib.enums_src.GameData_enums import Attribute, Profession, ProfessionAttributes
from Py4GWCoreLib.enums_src.Region_enums import ServerLanguage
from Py4GWCoreLib.enums_src.UI_enums import NumberPreference
from Sources.frenkeyLib.ItemHandling.item_modifiers import DecodedModifier
from Sources.frenkeyLib.ItemHandling.types import Upgrades

class ItemUpgradeClassType(IntEnum):
    Unknown = 0
    Prefix = 1
    Suffix = 2
    Inscription = 3
    UpgradeRune = 4
    AppliesToRune = 5

@dataclass
class ItemUpgradeBaseClass:
    upgrade_id : int
    
    def get_name(self, mod : DecodedModifier) -> str:
        return ""
    
    def get_description(self, mod : DecodedModifier) -> str:
        return ""
    
@dataclass
class ItemUpgradeClass(ItemUpgradeBaseClass):
    upgrade : Upgrades
    
    def __post_init__(self):
        self.names = self.upgrade.value.names
        self.descriptions = self.upgrade.value.descriptions
        self.upgrade_type = self.upgrade.value.upgrade_type
    
    def get_name(self, mod : DecodedModifier) -> str:
        preference = UIManager.GetIntPreference(NumberPreference.TextLanguage)
        server_language = ServerLanguage(preference)
        return self.names.get(server_language, self.names.get(ServerLanguage.English, self.__class__.__name__))
    
    def get_description(self, mod : DecodedModifier) -> str:
        preference = UIManager.GetIntPreference(NumberPreference.TextLanguage)
        server_language = ServerLanguage(preference)
        return self.descriptions.get(server_language, self.descriptions.get(ServerLanguage.English, ""))


@dataclass
class OfTheProfessionUpgradeClass(ItemUpgradeBaseClass):
    upgrade_id : int

    def get_profession_from_attribute(self, attribute: Attribute) -> Optional[Profession]:
        for prof, attr in ProfessionAttributes.__dict__.items():
            if isinstance(attr, list) and attribute in attr:
                return Profession[prof]
        return None

    def get_name(self, mod: DecodedModifier) -> str:
        profession = self.get_profession_from_attribute(Attribute(mod.arg1)) or Profession._None
        name_dict = {
            ServerLanguage.German: "d. des {profession}",
            ServerLanguage.English: "of the {profession}",
            ServerLanguage.Korean: "({profession})",
            ServerLanguage.French: "(le {profession})",
            ServerLanguage.Italian: "dell'arco il {profession}",
            ServerLanguage.Spanish: "(el {profession})",
            ServerLanguage.TraditionalChinese: "the {profession}",
            ServerLanguage.Japanese: "({profession})",
            ServerLanguage.Polish: "({profession})",
            ServerLanguage.Russian: "of {profession}",
            ServerLanguage.BorkBorkBork: "ooff zee {profession}"
        }
        
        name = name_dict.get(ServerLanguage(UIManager.GetIntPreference(NumberPreference.TextLanguage)), name_dict[ServerLanguage.English])
        return name.format(profession=profession.value if profession else "Unknown")
    
    def get_description(self, mod):
        description_dict = {
            ServerLanguage.English: "{attribute}: {attribute_level} (if your rank is lower. No effects in PvP.)"
            }
        attribute = Attribute(mod.arg1)
        attribute_level = mod.arg2
        
        description = description_dict.get(ServerLanguage(UIManager.GetIntPreference(NumberPreference.TextLanguage)), description_dict[ServerLanguage.English])
        return description.format(attribute=attribute.value if attribute else "Unknown", attribute_level=attribute_level)


class ItemUpgrade(Enum):
    Unknown = ItemUpgradeClass(upgrade_id = -1,  upgrade=Upgrades.Unknown)
    Icy_Axe = ItemUpgradeClass(upgrade_id = 0x0081,  upgrade=Upgrades.Icy)
    Ebon_Axe = ItemUpgradeClass(upgrade_id = 0x0082,  upgrade=Upgrades.Ebon)
    Shocking_Axe = ItemUpgradeClass(upgrade_id = 0x0083,  upgrade=Upgrades.Shocking)
    Fiery_Axe = ItemUpgradeClass(upgrade_id = 0x0084,  upgrade=Upgrades.Fiery)
    Barbed_Axe = ItemUpgradeClass(upgrade_id = 0x0092,  upgrade=Upgrades.Barbed)
    Crippling_Axe = ItemUpgradeClass(upgrade_id = 0x0094,  upgrade=Upgrades.Crippling)
    Cruel_Axe = ItemUpgradeClass(upgrade_id = 0x0096,  upgrade=Upgrades.Cruel)
    Furious_Axe = ItemUpgradeClass(upgrade_id = 0x0099,  upgrade=Upgrades.Furious)
    Poisonous_Axe = ItemUpgradeClass(upgrade_id = 0x009E,  upgrade=Upgrades.Poisonous)
    Heavy_Axe = ItemUpgradeClass(upgrade_id = 0x00A1,  upgrade=Upgrades.Heavy)
    Zealous_Axe = ItemUpgradeClass(upgrade_id = 0x00A3,  upgrade=Upgrades.Zealous)
    Vampiric_Axe = ItemUpgradeClass(upgrade_id = 0x00A7,  upgrade=Upgrades.Vampiric)
    Sundering_Axe = ItemUpgradeClass(upgrade_id = 0x00AB,  upgrade=Upgrades.Sundering)
    OfDefense_Axe = ItemUpgradeClass(upgrade_id = 0x00C5,  upgrade=Upgrades.OfDefense)
    OfWarding_Axe = ItemUpgradeClass(upgrade_id = 0x00C7,  upgrade=Upgrades.OfWarding)
    OfShelter_Axe = ItemUpgradeClass(upgrade_id = 0x00CD,  upgrade=Upgrades.OfShelter)
    OfSlaying_Axe = ItemUpgradeClass(upgrade_id = 0x00D4,  upgrade=Upgrades.OfSlaying)
    OfFortitude_Axe = ItemUpgradeClass(upgrade_id = 0x00D9,  upgrade=Upgrades.OfFortitude)
    OfEnchanting_Axe = ItemUpgradeClass(upgrade_id = 0x00DE,  upgrade=Upgrades.OfEnchanting)
    OfAxeMastery = ItemUpgradeClass(upgrade_id = 0x00E8,  upgrade=Upgrades.OfAxeMastery)
    OfTheProfession_Axe = OfTheProfessionUpgradeClass(upgrade_id = 0x0226)
    Icy_Bow = ItemUpgradeClass(upgrade_id = 0x0085,  upgrade=Upgrades.Icy)
    Ebon_Bow = ItemUpgradeClass(upgrade_id = 0x0086,  upgrade=Upgrades.Ebon)
    Shocking_Bow = ItemUpgradeClass(upgrade_id = 0x0087,  upgrade=Upgrades.Shocking)
    Fiery_Bow = ItemUpgradeClass(upgrade_id = 0x0088,  upgrade=Upgrades.Fiery)
    Poisonous_Bow = ItemUpgradeClass(upgrade_id = 0x009F,  upgrade=Upgrades.Poisonous)
    Zealous_Bow = ItemUpgradeClass(upgrade_id = 0x00A5,  upgrade=Upgrades.Zealous)
    Vampiric_Bow = ItemUpgradeClass(upgrade_id = 0x00A9,  upgrade=Upgrades.Vampiric)
    Sundering_Bow = ItemUpgradeClass(upgrade_id = 0x00AD,  upgrade=Upgrades.Sundering)
    OfDefense_Bow = ItemUpgradeClass(upgrade_id = 0x00C6,  upgrade=Upgrades.OfDefense)
    OfWarding_Bow = ItemUpgradeClass(upgrade_id = 0x00C8,  upgrade=Upgrades.OfWarding)
    OfShelter_Bow = ItemUpgradeClass(upgrade_id = 0x00CE,  upgrade=Upgrades.OfShelter)
    OfSlaying_Bow = ItemUpgradeClass(upgrade_id = 0x00D5,  upgrade=Upgrades.OfSlaying)
    OfFortitude_Bow = ItemUpgradeClass(upgrade_id = 0x00DA,  upgrade=Upgrades.OfFortitude)
    OfEnchanting_Bow = ItemUpgradeClass(upgrade_id = 0x00DF,  upgrade=Upgrades.OfEnchanting)
    OfMarksmanship = ItemUpgradeClass(upgrade_id = 0x00E9,  upgrade=Upgrades.OfMarksmanship)
    Barbed_Bow = ItemUpgradeClass(upgrade_id = 0x0147,  upgrade=Upgrades.Barbed)
    Crippling_Bow = ItemUpgradeClass(upgrade_id = 0x0148,  upgrade=Upgrades.Crippling)
    Silencing_Bow = ItemUpgradeClass(upgrade_id = 0x0149,  upgrade=Upgrades.Silencing)
    OfTheProfession_Bow = OfTheProfessionUpgradeClass(upgrade_id = 0x0227)
    Icy_Daggers = ItemUpgradeClass(upgrade_id = 0x012E,  upgrade=Upgrades.Icy)
    Ebon_Daggers = ItemUpgradeClass(upgrade_id = 0x012F,  upgrade=Upgrades.Ebon)
    Fiery_Daggers = ItemUpgradeClass(upgrade_id = 0x0130,  upgrade=Upgrades.Fiery)
    Shocking_Daggers = ItemUpgradeClass(upgrade_id = 0x0131,  upgrade=Upgrades.Shocking)
    Zealous_Daggers = ItemUpgradeClass(upgrade_id = 0x0132,  upgrade=Upgrades.Zealous)
    Vampiric_Daggers = ItemUpgradeClass(upgrade_id = 0x0133,  upgrade=Upgrades.Vampiric)
    Sundering_Daggers = ItemUpgradeClass(upgrade_id = 0x0134,  upgrade=Upgrades.Sundering)
    Barbed_Daggers = ItemUpgradeClass(upgrade_id = 0x0135,  upgrade=Upgrades.Barbed)
    Crippling_Daggers = ItemUpgradeClass(upgrade_id = 0x0136,  upgrade=Upgrades.Crippling)
    Cruel_Daggers = ItemUpgradeClass(upgrade_id = 0x0137,  upgrade=Upgrades.Cruel)
    Poisonous_Daggers = ItemUpgradeClass(upgrade_id = 0x0138,  upgrade=Upgrades.Poisonous)
    Silencing_Daggers = ItemUpgradeClass(upgrade_id = 0x0139,  upgrade=Upgrades.Silencing)
    Furious_Daggers = ItemUpgradeClass(upgrade_id = 0x013A,  upgrade=Upgrades.Furious)
    OfDefense_Daggers = ItemUpgradeClass(upgrade_id = 0x0141,  upgrade=Upgrades.OfDefense)
    OfWarding_Daggers = ItemUpgradeClass(upgrade_id = 0x0142,  upgrade=Upgrades.OfWarding)
    OfShelter_Daggers = ItemUpgradeClass(upgrade_id = 0x0143,  upgrade=Upgrades.OfShelter)
    OfEnchanting_Daggers = ItemUpgradeClass(upgrade_id = 0x0144,  upgrade=Upgrades.OfEnchanting)
    OfFortitude_Daggers = ItemUpgradeClass(upgrade_id = 0x0145,  upgrade=Upgrades.OfFortitude)
    OfDaggerMastery = ItemUpgradeClass(upgrade_id = 0x0146,  upgrade=Upgrades.OfDaggerMastery)
    OfTheProfession_Daggers = OfTheProfessionUpgradeClass(upgrade_id = 0x0228)
    OfAptitude_Focus = ItemUpgradeClass(upgrade_id = 0x0217,  upgrade=Upgrades.OfAptitude)
    OfFortitude_Focus = ItemUpgradeClass(upgrade_id = 0x0218,  upgrade=Upgrades.OfFortitude)
    OfDevotion_Focus = ItemUpgradeClass(upgrade_id = 0x0219,  upgrade=Upgrades.OfDevotion)
    OfValor_Focus = ItemUpgradeClass(upgrade_id = 0x021A,  upgrade=Upgrades.OfValor)
    OfEndurance_Focus = ItemUpgradeClass(upgrade_id = 0x021B,  upgrade=Upgrades.OfEndurance)
    OfSwiftness_Focus = ItemUpgradeClass(upgrade_id = 0x021C,  upgrade=Upgrades.OfSwiftness)
    Icy_Hammer = ItemUpgradeClass(upgrade_id = 0x0089,  upgrade=Upgrades.Icy)
    Ebon_Hammer = ItemUpgradeClass(upgrade_id = 0x008A,  upgrade=Upgrades.Ebon)
    Shocking_Hammer = ItemUpgradeClass(upgrade_id = 0x008B,  upgrade=Upgrades.Shocking)
    Fiery_Hammer = ItemUpgradeClass(upgrade_id = 0x008C,  upgrade=Upgrades.Fiery)
    Cruel_Hammer = ItemUpgradeClass(upgrade_id = 0x0097,  upgrade=Upgrades.Cruel)
    Furious_Hammer = ItemUpgradeClass(upgrade_id = 0x009A,  upgrade=Upgrades.Furious)
    Heavy_Hammer = ItemUpgradeClass(upgrade_id = 0x00A2,  upgrade=Upgrades.Heavy)
    Zealous_Hammer = ItemUpgradeClass(upgrade_id = 0x00A4,  upgrade=Upgrades.Zealous)
    Vampiric_Hammer = ItemUpgradeClass(upgrade_id = 0x00A8,  upgrade=Upgrades.Vampiric)
    Sundering_Hammer = ItemUpgradeClass(upgrade_id = 0x00AC,  upgrade=Upgrades.Sundering)
    OfWarding_Hammer = ItemUpgradeClass(upgrade_id = 0x00C9,  upgrade=Upgrades.OfWarding)
    OfDefense_Hammer = ItemUpgradeClass(upgrade_id = 0x00CC,  upgrade=Upgrades.OfDefense)
    OfShelter_Hammer = ItemUpgradeClass(upgrade_id = 0x00CF,  upgrade=Upgrades.OfShelter)
    OfSlaying_Hammer = ItemUpgradeClass(upgrade_id = 0x00D6,  upgrade=Upgrades.OfSlaying)
    OfFortitude_Hammer = ItemUpgradeClass(upgrade_id = 0x00DB,  upgrade=Upgrades.OfFortitude)
    OfEnchanting_Hammer = ItemUpgradeClass(upgrade_id = 0x00E0,  upgrade=Upgrades.OfEnchanting)
    OfHammerMastery = ItemUpgradeClass(upgrade_id = 0x00EA,  upgrade=Upgrades.OfHammerMastery)
    OfTheProfession_Hammer = OfTheProfessionUpgradeClass(upgrade_id = 0x0229)
    IHaveThePower = ItemUpgradeClass(upgrade_id = 0x015C,  upgrade=Upgrades.IHaveThePower)
    LetTheMemoryLiveAgain = ItemUpgradeClass(upgrade_id = 0x015E,  upgrade=Upgrades.LetTheMemoryLiveAgain)
    TooMuchInformation = ItemUpgradeClass(upgrade_id = 0x0163,  upgrade=Upgrades.TooMuchInformation)
    GuidedByFate = ItemUpgradeClass(upgrade_id = 0x0164,  upgrade=Upgrades.GuidedByFate)
    StrengthAndHonor = ItemUpgradeClass(upgrade_id = 0x0165,  upgrade=Upgrades.StrengthAndHonor)
    VengeanceIsMine = ItemUpgradeClass(upgrade_id = 0x0166,  upgrade=Upgrades.VengeanceIsMine)
    DontFearTheReaper = ItemUpgradeClass(upgrade_id = 0x0167,  upgrade=Upgrades.DontFearTheReaper)
    DanceWithDeath = ItemUpgradeClass(upgrade_id = 0x0168,  upgrade=Upgrades.DanceWithDeath)
    BrawnOverBrains = ItemUpgradeClass(upgrade_id = 0x0169,  upgrade=Upgrades.BrawnOverBrains)
    ToThePain = ItemUpgradeClass(upgrade_id = 0x016A,  upgrade=Upgrades.ToThePain)
    IgnoranceIsBliss = ItemUpgradeClass(upgrade_id = 0x01B6,  upgrade=Upgrades.IgnoranceIsBliss)
    LifeIsPain = ItemUpgradeClass(upgrade_id = 0x01B7,  upgrade=Upgrades.LifeIsPain)
    ManForAllSeasons = ItemUpgradeClass(upgrade_id = 0x01B8,  upgrade=Upgrades.ManForAllSeasons)
    SurvivalOfTheFittest = ItemUpgradeClass(upgrade_id = 0x01B9,  upgrade=Upgrades.SurvivalOfTheFittest)
    MightMakesRight = ItemUpgradeClass(upgrade_id = 0x01BA,  upgrade=Upgrades.MightMakesRight)
    KnowingIsHalfTheBattle = ItemUpgradeClass(upgrade_id = 0x01BB,  upgrade=Upgrades.KnowingIsHalfTheBattle)
    FaithIsMyShield = ItemUpgradeClass(upgrade_id = 0x01BC,  upgrade=Upgrades.FaithIsMyShield)
    DownButNotOut = ItemUpgradeClass(upgrade_id = 0x01BD,  upgrade=Upgrades.DownButNotOut)
    HailToTheKing = ItemUpgradeClass(upgrade_id = 0x01BE,  upgrade=Upgrades.HailToTheKing)
    BeJustAndFearNot = ItemUpgradeClass(upgrade_id = 0x01BF,  upgrade=Upgrades.BeJustAndFearNot)
    LiveForToday = ItemUpgradeClass(upgrade_id = 0x01C0,  upgrade=Upgrades.LiveForToday)
    SerenityNow = ItemUpgradeClass(upgrade_id = 0x01C1,  upgrade=Upgrades.SerenityNow)
    ForgetMeNot = ItemUpgradeClass(upgrade_id = 0x01C2,  upgrade=Upgrades.ForgetMeNot)
    NotTheFace = ItemUpgradeClass(upgrade_id = 0x01C3,  upgrade=Upgrades.NotTheFace)
    LeafOnTheWind = ItemUpgradeClass(upgrade_id = 0x01C4,  upgrade=Upgrades.LeafOnTheWind)
    LikeARollingStone = ItemUpgradeClass(upgrade_id = 0x01C5,  upgrade=Upgrades.LikeARollingStone)
    RidersOnTheStorm = ItemUpgradeClass(upgrade_id = 0x01C6,  upgrade=Upgrades.RidersOnTheStorm)
    SleepNowInTheFire = ItemUpgradeClass(upgrade_id = 0x01C7,  upgrade=Upgrades.SleepNowInTheFire)
    ThroughThickAndThin = ItemUpgradeClass(upgrade_id = 0x01C8,  upgrade=Upgrades.ThroughThickAndThin)
    TheRiddleOfSteel = ItemUpgradeClass(upgrade_id = 0x01C9,  upgrade=Upgrades.TheRiddleOfSteel)
    FearCutsDeeper = ItemUpgradeClass(upgrade_id = 0x01CA,  upgrade=Upgrades.FearCutsDeeper)
    ICanSeeClearlyNow = ItemUpgradeClass(upgrade_id = 0x01CB,  upgrade=Upgrades.ICanSeeClearlyNow)
    SwiftAsTheWind = ItemUpgradeClass(upgrade_id = 0x01CC,  upgrade=Upgrades.SwiftAsTheWind)
    StrengthOfBody = ItemUpgradeClass(upgrade_id = 0x01CD,  upgrade=Upgrades.StrengthOfBody)
    CastOutTheUnclean = ItemUpgradeClass(upgrade_id = 0x01CE,  upgrade=Upgrades.CastOutTheUnclean)
    PureOfHeart = ItemUpgradeClass(upgrade_id = 0x01CF,  upgrade=Upgrades.PureOfHeart)
    SoundnessOfMind = ItemUpgradeClass(upgrade_id = 0x01D0,  upgrade=Upgrades.SoundnessOfMind)
    OnlyTheStrongSurvive = ItemUpgradeClass(upgrade_id = 0x01D1,  upgrade=Upgrades.OnlyTheStrongSurvive)
    LuckOfTheDraw = ItemUpgradeClass(upgrade_id = 0x01D2,  upgrade=Upgrades.LuckOfTheDraw)
    ShelteredByFaith = ItemUpgradeClass(upgrade_id = 0x01D3,  upgrade=Upgrades.ShelteredByFaith)
    NothingToFear = ItemUpgradeClass(upgrade_id = 0x01D4,  upgrade=Upgrades.NothingToFear)
    RunForYourLife = ItemUpgradeClass(upgrade_id = 0x01D5,  upgrade=Upgrades.RunForYourLife)
    MasterOfMyDomain = ItemUpgradeClass(upgrade_id = 0x01D6,  upgrade=Upgrades.MasterOfMyDomain)
    AptitudeNotAttitude = ItemUpgradeClass(upgrade_id = 0x01D7,  upgrade=Upgrades.AptitudeNotAttitude)
    SeizeTheDay = ItemUpgradeClass(upgrade_id = 0x01D8,  upgrade=Upgrades.SeizeTheDay)
    HaveFaith = ItemUpgradeClass(upgrade_id = 0x01D9,  upgrade=Upgrades.HaveFaith)
    HaleAndHearty = ItemUpgradeClass(upgrade_id = 0x01DA,  upgrade=Upgrades.HaleAndHearty)
    DontCallItAComeback = ItemUpgradeClass(upgrade_id = 0x01DB,  upgrade=Upgrades.DontCallItAComback)
    IAmSorrow = ItemUpgradeClass(upgrade_id = 0x01DC,  upgrade=Upgrades.IAmSorrow)
    DontThinkTwice = ItemUpgradeClass(upgrade_id = 0x01DD,  upgrade=Upgrades.DontThinkTwice)
    ShowMeTheMoney = ItemUpgradeClass(upgrade_id = 0x021E,  upgrade=Upgrades.ShowMeTheMoney)
    MeasureForMeasure = ItemUpgradeClass(upgrade_id = 0x021F,  upgrade=Upgrades.MeasureForMeasure)
    Icy_Scythe = ItemUpgradeClass(upgrade_id = 0x016B,  upgrade=Upgrades.Icy)
    Ebon_Scythe = ItemUpgradeClass(upgrade_id = 0x016C,  upgrade=Upgrades.Ebon)
    Zealous_Scythe = ItemUpgradeClass(upgrade_id = 0x016F,  upgrade=Upgrades.Zealous)
    Vampiric_Scythe = ItemUpgradeClass(upgrade_id = 0x0171,  upgrade=Upgrades.Vampiric)
    Sundering_Scythe = ItemUpgradeClass(upgrade_id = 0x0173,  upgrade=Upgrades.Sundering)
    Barbed_Scythe = ItemUpgradeClass(upgrade_id = 0x0174,  upgrade=Upgrades.Barbed)
    Crippling_Scythe = ItemUpgradeClass(upgrade_id = 0x0175,  upgrade=Upgrades.Crippling)
    Cruel_Scythe = ItemUpgradeClass(upgrade_id = 0x0176,  upgrade=Upgrades.Cruel)
    Poisonous_Scythe = ItemUpgradeClass(upgrade_id = 0x0177,  upgrade=Upgrades.Poisonous)
    Heavy_Scythe = ItemUpgradeClass(upgrade_id = 0x0178,  upgrade=Upgrades.Heavy)
    Furious_Scythe = ItemUpgradeClass(upgrade_id = 0x0179,  upgrade=Upgrades.Furious)
    OfDefense_Scythe = ItemUpgradeClass(upgrade_id = 0x0188,  upgrade=Upgrades.OfDefense)
    OfWarding_Scythe = ItemUpgradeClass(upgrade_id = 0x0189,  upgrade=Upgrades.OfWarding)
    OfShelter_Scythe = ItemUpgradeClass(upgrade_id = 0x018A,  upgrade=Upgrades.OfShelter)
    OfEnchanting_Scythe = ItemUpgradeClass(upgrade_id = 0x018B,  upgrade=Upgrades.OfEnchanting)
    OfFortitude_Scythe = ItemUpgradeClass(upgrade_id = 0x018C,  upgrade=Upgrades.OfFortitude)
    OfScytheMastery = ItemUpgradeClass(upgrade_id = 0x018D,  upgrade=Upgrades.OfScytheMastery)
    Fiery_Scythe = ItemUpgradeClass(upgrade_id = 0x020B,  upgrade=Upgrades.Fiery)
    Shocking_Scythe = ItemUpgradeClass(upgrade_id = 0x020C,  upgrade=Upgrades.Shocking)
    OfTheProfession_Scythe = OfTheProfessionUpgradeClass(upgrade_id = 0x022C)
    OfValor_Shield = ItemUpgradeClass(upgrade_id = 0x0151,  upgrade=Upgrades.OfValor)
    OfEndurance_Shield = ItemUpgradeClass(upgrade_id = 0x0152,  upgrade=Upgrades.OfEndurance)
    OfFortitude_Shield = ItemUpgradeClass(upgrade_id = 0x0161,  upgrade=Upgrades.OfFortitude)
    OfDevotion_Shield = ItemUpgradeClass(upgrade_id = 0x0162,  upgrade=Upgrades.OfDevotion)
    Fiery_Spear = ItemUpgradeClass(upgrade_id = 0x016D,  upgrade=Upgrades.Fiery)
    Shocking_Spear = ItemUpgradeClass(upgrade_id = 0x016E,  upgrade=Upgrades.Shocking)
    Zealous_Spear = ItemUpgradeClass(upgrade_id = 0x0170,  upgrade=Upgrades.Zealous)
    Vampiric_Spear = ItemUpgradeClass(upgrade_id = 0x0172,  upgrade=Upgrades.Vampiric)
    Sundering_Spear = ItemUpgradeClass(upgrade_id = 0x017A,  upgrade=Upgrades.Sundering)
    Barbed_Spear = ItemUpgradeClass(upgrade_id = 0x017B,  upgrade=Upgrades.Barbed)
    Crippling_Spear = ItemUpgradeClass(upgrade_id = 0x017C,  upgrade=Upgrades.Crippling)
    Cruel_Spear = ItemUpgradeClass(upgrade_id = 0x017D,  upgrade=Upgrades.Cruel)
    Poisonous_Spear = ItemUpgradeClass(upgrade_id = 0x017E,  upgrade=Upgrades.Poisonous)
    Silencing_Spear = ItemUpgradeClass(upgrade_id = 0x017F,  upgrade=Upgrades.Silencing)
    Furious_Spear = ItemUpgradeClass(upgrade_id = 0x0180,  upgrade=Upgrades.Furious)
    Heavy_Spear = ItemUpgradeClass(upgrade_id = 0x0181,  upgrade=Upgrades.Heavy)
    OfDefense_Spear = ItemUpgradeClass(upgrade_id = 0x018E,  upgrade=Upgrades.OfDefense)
    OfWarding_Spear = ItemUpgradeClass(upgrade_id = 0x018F,  upgrade=Upgrades.OfWarding)
    OfShelter_Spear = ItemUpgradeClass(upgrade_id = 0x0190,  upgrade=Upgrades.OfShelter)
    OfEnchanting_Spear = ItemUpgradeClass(upgrade_id = 0x0191,  upgrade=Upgrades.OfEnchanting)
    OfFortitude_Spear = ItemUpgradeClass(upgrade_id = 0x0192,  upgrade=Upgrades.OfFortitude)
    OfSpearMastery = ItemUpgradeClass(upgrade_id = 0x0193,  upgrade=Upgrades.OfSpearMastery)
    Icy_Spear = ItemUpgradeClass(upgrade_id = 0x020D,  upgrade=Upgrades.Icy)
    Ebon_Spear = ItemUpgradeClass(upgrade_id = 0x020E,  upgrade=Upgrades.Ebon)
    OfTheProfession_Spear = OfTheProfessionUpgradeClass(upgrade_id = 0x022D)
    Defensive_Staff = ItemUpgradeClass(upgrade_id = 0x0091,  upgrade=Upgrades.Defensive)
    Insightful_Staff = ItemUpgradeClass(upgrade_id = 0x009C,  upgrade=Upgrades.Insightful)
    Hale_Staff = ItemUpgradeClass(upgrade_id = 0x009D,  upgrade=Upgrades.Hale)
    OfAttribute_Staff = ItemUpgradeClass(upgrade_id = 0x00C3,  upgrade=Upgrades.OfAttribute)
    OfWarding_Staff = ItemUpgradeClass(upgrade_id = 0x00CA,  upgrade=Upgrades.OfWarding)
    OfShelter_Staff = ItemUpgradeClass(upgrade_id = 0x00D0,  upgrade=Upgrades.OfShelter)
    OfDefense_Staff = ItemUpgradeClass(upgrade_id = 0x00D2,  upgrade=Upgrades.OfDefense)
    OfSlaying_Staff = ItemUpgradeClass(upgrade_id = 0x00D7,  upgrade=Upgrades.OfSlaying)
    OfFortitude_Staff = ItemUpgradeClass(upgrade_id = 0x00DC,  upgrade=Upgrades.OfFortitude)
    OfEnchanting_Staff = ItemUpgradeClass(upgrade_id = 0x00E1,  upgrade=Upgrades.OfEnchanting)
    OfMastery_Staff = ItemUpgradeClass(upgrade_id = 0x0153,  upgrade=Upgrades.OfMastery)
    OfDevotion_Staff = ItemUpgradeClass(upgrade_id = 0x0154,  upgrade=Upgrades.OfDevotion)
    OfValor_Staff = ItemUpgradeClass(upgrade_id = 0x0155,  upgrade=Upgrades.OfValor)
    OfEndurance_Staff = ItemUpgradeClass(upgrade_id = 0x0156,  upgrade=Upgrades.OfEndurance)
    Swift_Staff = ItemUpgradeClass(upgrade_id = 0x020F,  upgrade=Upgrades.Swift)
    Adept_Staff = ItemUpgradeClass(upgrade_id = 0x0210,  upgrade=Upgrades.Adept)
    OfTheProfession_Staff = OfTheProfessionUpgradeClass(upgrade_id = 0x022B)
    Icy_Sword = ItemUpgradeClass(upgrade_id = 0x008D,  upgrade=Upgrades.Icy)
    Ebon_Sword = ItemUpgradeClass(upgrade_id = 0x008E,  upgrade=Upgrades.Ebon)
    Shocking_Sword = ItemUpgradeClass(upgrade_id = 0x008F,  upgrade=Upgrades.Shocking)
    Fiery_Sword = ItemUpgradeClass(upgrade_id = 0x0090,  upgrade=Upgrades.Fiery)
    Barbed_Sword = ItemUpgradeClass(upgrade_id = 0x0093,  upgrade=Upgrades.Barbed)
    Crippling_Sword = ItemUpgradeClass(upgrade_id = 0x0095,  upgrade=Upgrades.Crippling)
    Cruel_Sword = ItemUpgradeClass(upgrade_id = 0x0098,  upgrade=Upgrades.Cruel)
    Furious_Sword = ItemUpgradeClass(upgrade_id = 0x009B,  upgrade=Upgrades.Furious)
    Poisonous_Sword = ItemUpgradeClass(upgrade_id = 0x00A0,  upgrade=Upgrades.Poisonous)
    Zealous_Sword = ItemUpgradeClass(upgrade_id = 0x00A6,  upgrade=Upgrades.Zealous)
    Vampiric_Sword = ItemUpgradeClass(upgrade_id = 0x00AA,  upgrade=Upgrades.Vampiric)
    Sundering_Sword = ItemUpgradeClass(upgrade_id = 0x00AE,  upgrade=Upgrades.Sundering)
    OfWarding_Sword = ItemUpgradeClass(upgrade_id = 0x00CB,  upgrade=Upgrades.OfWarding)
    OfShelter_Sword = ItemUpgradeClass(upgrade_id = 0x00D1,  upgrade=Upgrades.OfShelter)
    OfDefense_Sword = ItemUpgradeClass(upgrade_id = 0x00D3,  upgrade=Upgrades.OfDefense)
    OfSlaying_Sword = ItemUpgradeClass(upgrade_id = 0x00D8,  upgrade=Upgrades.OfSlaying)
    OfFortitude_Sword = ItemUpgradeClass(upgrade_id = 0x00DD,  upgrade=Upgrades.OfFortitude)
    OfEnchanting_Sword = ItemUpgradeClass(upgrade_id = 0x00E2,  upgrade=Upgrades.OfEnchanting)
    OfSwordsmanship = ItemUpgradeClass(upgrade_id = 0x00EB,  upgrade=Upgrades.OfSwordsmanship)
    OfTheProfession_Sword = OfTheProfessionUpgradeClass(upgrade_id = 0x022E)
    OfMemory_Wand = ItemUpgradeClass(upgrade_id = 0x015F,  upgrade=Upgrades.OfMemory)
    OfQuickening_Wand = ItemUpgradeClass(upgrade_id = 0x0160,  upgrade=Upgrades.OfQuickening)
    OfTheProfession_Wand = OfTheProfessionUpgradeClass(upgrade_id = 0x022A)
    Survivor = ItemUpgradeClass(upgrade_id = 0x01E6,  upgrade=Upgrades.Survivor)
    Radiant = ItemUpgradeClass(upgrade_id = 0x01E5,  upgrade=Upgrades.Radiant)
    Stalwart = ItemUpgradeClass(upgrade_id = 0x01E7,  upgrade=Upgrades.Stalwart)
    Brawlers = ItemUpgradeClass(upgrade_id = 0x01E8,  upgrade=Upgrades.Brawlers)
    Blessed = ItemUpgradeClass(upgrade_id = 0x01E9,  upgrade=Upgrades.Blessed)
    Heralds = ItemUpgradeClass(upgrade_id = 0x01EA,  upgrade=Upgrades.Heralds)
    Sentrys = ItemUpgradeClass(upgrade_id = 0x01EB,  upgrade=Upgrades.Sentrys)
    Knights = ItemUpgradeClass(upgrade_id = 0x01F9,  upgrade=Upgrades.Knights)
    Lieutenants = ItemUpgradeClass(upgrade_id = 0x0208,  upgrade=Upgrades.Lieutenants)
    Stonefist = ItemUpgradeClass(upgrade_id = 0x0209,  upgrade=Upgrades.Stonefist)
    Dreadnought = ItemUpgradeClass(upgrade_id = 0x01FA,  upgrade=Upgrades.Dreadnought)
    Sentinels = ItemUpgradeClass(upgrade_id = 0x01FB,  upgrade=Upgrades.Sentinels)
    Frostbound = ItemUpgradeClass(upgrade_id = 0x01FC,  name = "Frostbound", upgrade_type = ItemUpgradeClassType.Prefix)
    Pyrebound = ItemUpgradeClass(upgrade_id = 0x01FE,  name = "Pyrebound", upgrade_type = ItemUpgradeClassType.Prefix)
    Stormbound = ItemUpgradeClass(upgrade_id = 0x01FF,  name = "Stormbound", upgrade_type = ItemUpgradeClassType.Prefix)
    Scouts = ItemUpgradeClass(upgrade_id = 0x0201,  name = "Scout's", upgrade_type = ItemUpgradeClassType.Prefix)
    Earthbound = ItemUpgradeClass(upgrade_id = 0x01FD,  name = "Earthbound", upgrade_type = ItemUpgradeClassType.Prefix)
    Beastmasters = ItemUpgradeClass(upgrade_id = 0x0200,  name = "Beastmaster's", upgrade_type = ItemUpgradeClassType.Prefix)
    Wanderers = ItemUpgradeClass(upgrade_id = 0x01F6,  name = "Wanderer's", upgrade_type = ItemUpgradeClassType.Prefix)
    Disciples = ItemUpgradeClass(upgrade_id = 0x01F7,  name = "Disciple's", upgrade_type = ItemUpgradeClassType.Prefix)
    Anchorites = ItemUpgradeClass(upgrade_id = 0x01F8,  name = "Anchorite's", upgrade_type = ItemUpgradeClassType.Prefix)
    Bloodstained = ItemUpgradeClass(upgrade_id = 0x020A,  name = "Bloodstained", upgrade_type = ItemUpgradeClassType.Prefix)
    Tormentors = ItemUpgradeClass(upgrade_id = 0x01EC,  name = "Tormentor's", upgrade_type = ItemUpgradeClassType.Prefix)
    Bonelace = ItemUpgradeClass(upgrade_id = 0x01EE,  name = "Bonelace", upgrade_type = ItemUpgradeClassType.Prefix)
    MinionMasters = ItemUpgradeClass(upgrade_id = 0x01EF,  name = "Minion Master's", upgrade_type = ItemUpgradeClassType.Prefix)
    Blighters = ItemUpgradeClass(upgrade_id = 0x01F0,  name = "Blighter's", upgrade_type = ItemUpgradeClassType.Prefix)
    Undertakers = ItemUpgradeClass(upgrade_id = 0x01ED,  name = "Undertaker's", upgrade_type = ItemUpgradeClassType.Prefix)
    Virtuosos = ItemUpgradeClass(upgrade_id = 0x01E4,  name = "Virtuoso's", upgrade_type = ItemUpgradeClassType.Prefix)
    Artificers = ItemUpgradeClass(upgrade_id = 0x01E2,  name = "Artificer's", upgrade_type = ItemUpgradeClassType.Prefix)
    Prodigys = ItemUpgradeClass(upgrade_id = 0x01E3,  name = "Prodigy's", upgrade_type = ItemUpgradeClassType.Prefix)
    Hydromancer = ItemUpgradeClass(upgrade_id = 0x01F2,  name = "Hydromancer", upgrade_type = ItemUpgradeClassType.Prefix)
    Geomancer = ItemUpgradeClass(upgrade_id = 0x01F3,  name = "Geomancer", upgrade_type = ItemUpgradeClassType.Prefix)
    Pyromancer = ItemUpgradeClass(upgrade_id = 0x01F4,  name = "Pyromancer", upgrade_type = ItemUpgradeClassType.Prefix)
    Aeromancer = ItemUpgradeClass(upgrade_id = 0x01F5,  name = "Aeromancer", upgrade_type = ItemUpgradeClassType.Prefix)
    Prismatic = ItemUpgradeClass(upgrade_id = 0x01F1,  name = "Prismatic", upgrade_type = ItemUpgradeClassType.Prefix)
    Vanguards = ItemUpgradeClass(upgrade_id = 0x01DE,  name = "Vanguard's", upgrade_type = ItemUpgradeClassType.Prefix)
    Infiltrators = ItemUpgradeClass(upgrade_id = 0x01DF,  name = "Infiltrator's", upgrade_type = ItemUpgradeClassType.Prefix)
    Saboteurs = ItemUpgradeClass(upgrade_id = 0x01E0,  name = "Saboteur's", upgrade_type = ItemUpgradeClassType.Prefix)
    Nightstalkers = ItemUpgradeClass(upgrade_id = 0x01E1,  name = "Nightstalker's", upgrade_type = ItemUpgradeClassType.Prefix)
    Shamans = ItemUpgradeClass(upgrade_id = 0x0204,  name = "Shaman's", upgrade_type = ItemUpgradeClassType.Prefix)
    GhostForge = ItemUpgradeClass(upgrade_id = 0x0205,  name = "Ghost Forge", upgrade_type = ItemUpgradeClassType.Prefix)
    Mystics = ItemUpgradeClass(upgrade_id = 0x0206,  name = "Mystic's", upgrade_type = ItemUpgradeClassType.Prefix)
    Windwalker = ItemUpgradeClass(upgrade_id = 0x0202,  name = "Windwalker", upgrade_type = ItemUpgradeClassType.Prefix)
    Forsaken = ItemUpgradeClass(upgrade_id = 0x0203,  name = "Forsaken", upgrade_type = ItemUpgradeClassType.Prefix)
    Centurions = ItemUpgradeClass(upgrade_id = 0x0207,  name = "Centurion's", upgrade_type = ItemUpgradeClassType.Prefix)
    OfAttunement = ItemUpgradeClass(upgrade_id = 0x0211,  name = "of Attunement", upgrade_type = ItemUpgradeClassType.Suffix)
    OfRecovery = ItemUpgradeClass(upgrade_id = 0x0213,  name = "of Recovery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfRestoration = ItemUpgradeClass(upgrade_id = 0x0214,  name = "of Restoration", upgrade_type = ItemUpgradeClassType.Suffix)
    OfClarity = ItemUpgradeClass(upgrade_id = 0x0215,  name = "of Clarity", upgrade_type = ItemUpgradeClassType.Suffix)
    OfPurity = ItemUpgradeClass(upgrade_id = 0x0216,  name = "of Purity", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorVigor = ItemUpgradeClass(upgrade_id = 0x00FF,  name = "of Minor Vigor", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorVigor2 = ItemUpgradeClass(upgrade_id = 0x00C2,  name = "of Minor Vigor", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorVigor = ItemUpgradeClass(upgrade_id = 0x0101,  name = "of Superior Vigor", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorVigor = ItemUpgradeClass(upgrade_id = 0x0100,  name = "of Major Vigor", upgrade_type = ItemUpgradeClassType.Suffix)
    OfVitae = ItemUpgradeClass(upgrade_id = 0x0212,  name = "of Vitae", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorAbsorption = ItemUpgradeClass(upgrade_id = 0x00FC,  name = "of Minor Absorption", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorTactics = ItemUpgradeClass(upgrade_id = 0x1501,  name = "of Minor Tactics", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorStrength = ItemUpgradeClass(upgrade_id = 0x1101,  name = "of Minor Strength", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorAxeMastery = ItemUpgradeClass(upgrade_id = 0x1201,  name = "of Minor Axe Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorHammerMastery = ItemUpgradeClass(upgrade_id = 0x1301,  name = "of Minor Hammer Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorSwordsmanship = ItemUpgradeClass(upgrade_id = 0x1401,  name = "of Minor Swordsmanship", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorAbsorption = ItemUpgradeClass(upgrade_id = 0x00FD,  name = "of Major Absorption", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorTactics = ItemUpgradeClass(upgrade_id = 0x1502,  name = "of Major Tactics", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorStrength = ItemUpgradeClass(upgrade_id = 0x1102,  name = "of Major Strength", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorAxeMastery = ItemUpgradeClass(upgrade_id = 0x1202,  name = "of Major Axe Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorHammerMastery = ItemUpgradeClass(upgrade_id = 0x1302,  name = "of Major Hammer Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorSwordsmanship = ItemUpgradeClass(upgrade_id = 0x1402,  name = "of Major Swordsmanship", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorAbsorption = ItemUpgradeClass(upgrade_id = 0x00FE,  name = "of Superior Absorption", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorTactics = ItemUpgradeClass(upgrade_id = 0x1503,  name = "of Superior Tactics", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorStrength = ItemUpgradeClass(upgrade_id = 0x1103,  name = "of Superior Strength", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorAxeMastery = ItemUpgradeClass(upgrade_id = 0x1203,  name = "of Superior Axe Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorHammerMastery = ItemUpgradeClass(upgrade_id = 0x1303,  name = "of Superior Hammer Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorSwordsmanship = ItemUpgradeClass(upgrade_id = 0x1403,  name = "of Superior Swordsmanship", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorWildernessSurvival = ItemUpgradeClass(upgrade_id = 0x1801,  name = "of Minor Wilderness Survival", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorExpertise = ItemUpgradeClass(upgrade_id = 0x1701,  name = "of Minor Expertise", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorBeastMastery = ItemUpgradeClass(upgrade_id = 0x1601,  name = "of Minor Beast Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorMarksmanship = ItemUpgradeClass(upgrade_id = 0x1901,  name = "of Minor Marksmanship", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorWildernessSurvival = ItemUpgradeClass(upgrade_id = 0x1802,  name = "of Major Wilderness Survival", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorExpertise = ItemUpgradeClass(upgrade_id = 0x1702,  name = "of Major Expertise", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorBeastMastery = ItemUpgradeClass(upgrade_id = 0x1602,  name = "of Major Beast Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorMarksmanship = ItemUpgradeClass(upgrade_id = 0x1902,  name = "of Major Marksmanship", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorWildernessSurvival = ItemUpgradeClass(upgrade_id = 0x1803,  name = "of Superior Wilderness Survival", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorExpertise = ItemUpgradeClass(upgrade_id = 0x1703,  name = "of Superior Expertise", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorBeastMastery = ItemUpgradeClass(upgrade_id = 0x1603,  name = "of Superior Beast Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorMarksmanship = ItemUpgradeClass(upgrade_id = 0x1903,  name = "of Superior Marksmanship", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorHealingPrayers = ItemUpgradeClass(upgrade_id = 0x0D01,  name = "of Minor Healing Prayers", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorSmitingPrayers = ItemUpgradeClass(upgrade_id = 0x0E01,  name = "of Minor Smiting Prayers", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorProtectionPrayers = ItemUpgradeClass(upgrade_id = 0x0F01,  name = "of Minor Protection Prayers", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorDivineFavor = ItemUpgradeClass(upgrade_id = 0x1001,  name = "of Minor Divine Favor", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorHealingPrayers = ItemUpgradeClass(upgrade_id = 0x0D02,  name = "of Major Healing Prayers", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorSmitingPrayers = ItemUpgradeClass(upgrade_id = 0x0E02,  name = "of Major Smiting Prayers", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorProtectionPrayers = ItemUpgradeClass(upgrade_id = 0x0F02,  name = "of Major Protection Prayers", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorDivineFavor = ItemUpgradeClass(upgrade_id = 0x1002,  name = "of Major Divine Favor", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorHealingPrayers = ItemUpgradeClass(upgrade_id = 0x0D03,  name = "of Superior Healing Prayers", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorSmitingPrayers = ItemUpgradeClass(upgrade_id = 0x0E03,  name = "of Superior Smiting Prayers", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorProtectionPrayers = ItemUpgradeClass(upgrade_id = 0x0F03,  name = "of Superior Protection Prayers", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorDivineFavor = ItemUpgradeClass(upgrade_id = 0x1003,  name = "of Superior Divine Favor", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorBloodMagic = ItemUpgradeClass(upgrade_id = 0x0401,  name = "of Minor Blood Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorDeathMagic = ItemUpgradeClass(upgrade_id = 0x0501,  name = "of Minor Death Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorCurses = ItemUpgradeClass(upgrade_id = 0x0701,  name = "of Minor Curses", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorSoulReaping = ItemUpgradeClass(upgrade_id = 0x0601,  name = "of Minor Soul Reaping", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorBloodMagic = ItemUpgradeClass(upgrade_id = 0x0402,  name = "of Major Blood Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorDeathMagic = ItemUpgradeClass(upgrade_id = 0x0502,  name = "of Major Death Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorCurses = ItemUpgradeClass(upgrade_id = 0x0702,  name = "of Major Curses", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorSoulReaping = ItemUpgradeClass(upgrade_id = 0x0602,  name = "of Major Soul Reaping", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorBloodMagic = ItemUpgradeClass(upgrade_id = 0x0403,  name = "of Superior Blood Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorDeathMagic = ItemUpgradeClass(upgrade_id = 0x0503,  name = "of Superior Death Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorCurses = ItemUpgradeClass(upgrade_id = 0x0703,  name = "of Superior Curses", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorSoulReaping = ItemUpgradeClass(upgrade_id = 0x0603,  name = "of Superior Soul Reaping", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorFastCasting = ItemUpgradeClass(upgrade_id = 0x0001,  name = "of Minor Fast Casting", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorDominationMagic = ItemUpgradeClass(upgrade_id = 0x0201,  name = "of Minor Domination Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorIllusionMagic = ItemUpgradeClass(upgrade_id = 0x0101,  name = "of Minor Illusion Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorInspirationMagic = ItemUpgradeClass(upgrade_id = 0x0301,  name = "of Minor Inspiration Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorFastCasting = ItemUpgradeClass(upgrade_id = 0x0002,  name = "of Major Fast Casting", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorDominationMagic = ItemUpgradeClass(upgrade_id = 0x0202,  name = "of Major Domination Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorIllusionMagic = ItemUpgradeClass(upgrade_id = 0x0102,  name = "of Major Illusion Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorInspirationMagic = ItemUpgradeClass(upgrade_id = 0x0302,  name = "of Major Inspiration Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorFastCasting = ItemUpgradeClass(upgrade_id = 0x0003,  name = "of Superior Fast Casting", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorDominationMagic = ItemUpgradeClass(upgrade_id = 0x0203,  name = "of Superior Domination Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorIllusionMagic = ItemUpgradeClass(upgrade_id = 0x0103,  name = "of Superior Illusion Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorInspirationMagic = ItemUpgradeClass(upgrade_id = 0x0303,  name = "of Superior Inspiration Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorEnergyStorage = ItemUpgradeClass(upgrade_id = 0x0C01,  name = "of Minor Energy Storage", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorFireMagic = ItemUpgradeClass(upgrade_id = 0x0A01,  name = "of Minor Fire Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorAirMagic = ItemUpgradeClass(upgrade_id = 0x0801,  name = "of Minor Air Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorEarthMagic = ItemUpgradeClass(upgrade_id = 0x0901,  name = "of Minor Earth Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorWaterMagic = ItemUpgradeClass(upgrade_id = 0x0B01,  name = "of Minor Water Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorEnergyStorage = ItemUpgradeClass(upgrade_id = 0x0C02,  name = "of Major Energy Storage", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorFireMagic = ItemUpgradeClass(upgrade_id = 0x0A02,  name = "of Major Fire Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorAirMagic = ItemUpgradeClass(upgrade_id = 0x0802,  name = "of Major Air Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorEarthMagic = ItemUpgradeClass(upgrade_id = 0x0902,  name = "of Major Earth Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorWaterMagic = ItemUpgradeClass(upgrade_id = 0x0B02,  name = "of Major Water Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorEnergyStorage = ItemUpgradeClass(upgrade_id = 0x0C03,  name = "of Superior Energy Storage", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorFireMagic = ItemUpgradeClass(upgrade_id = 0x0A03,  name = "of Superior Fire Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorAirMagic = ItemUpgradeClass(upgrade_id = 0x0803,  name = "of Superior Air Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorEarthMagic = ItemUpgradeClass(upgrade_id = 0x0903,  name = "of Superior Earth Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorWaterMagic = ItemUpgradeClass(upgrade_id = 0x0B03,  name = "of Superior Water Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorCriticalStrikes = ItemUpgradeClass(upgrade_id = 0x2301,  name = "of Minor Critical Strikes", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorDaggerMastery = ItemUpgradeClass(upgrade_id = 0x1D01,  name = "of Minor Dagger Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorDeadlyArts = ItemUpgradeClass(upgrade_id = 0x1E01,  name = "of Minor Deadly Arts", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorShadowArts = ItemUpgradeClass(upgrade_id = 0x1F01,  name = "of Minor Shadow Arts", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorCriticalStrikes = ItemUpgradeClass(upgrade_id = 0x2302,  name = "of Major Critical Strikes", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorDaggerMastery = ItemUpgradeClass(upgrade_id = 0x1D02,  name = "of Major Dagger Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorDeadlyArts = ItemUpgradeClass(upgrade_id = 0x1E02,  name = "of Major Deadly Arts", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorShadowArts = ItemUpgradeClass(upgrade_id = 0x1F02,  name = "of Major Shadow Arts", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorCriticalStrikes = ItemUpgradeClass(upgrade_id = 0x2303,  name = "of Superior Critical Strikes", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorDaggerMastery = ItemUpgradeClass(upgrade_id = 0x1D03,  name = "of Superior Dagger Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorDeadlyArts = ItemUpgradeClass(upgrade_id = 0x1E03,  name = "of Superior Deadly Arts", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorShadowArts = ItemUpgradeClass(upgrade_id = 0x1F03,  name = "of Superior Shadow Arts", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorChannelingMagic = ItemUpgradeClass(upgrade_id = 0x2201,  name = "of Minor Channeling Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorRestorationMagic = ItemUpgradeClass(upgrade_id = 0x2101,  name = "of Minor Restoration Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorCommuning = ItemUpgradeClass(upgrade_id = 0x2001,  name = "of Minor Communing", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorSpawningPower = ItemUpgradeClass(upgrade_id = 0x2401,  name = "of Minor Spawning Power", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorChannelingMagic = ItemUpgradeClass(upgrade_id = 0x2202,  name = "of Major Channeling Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorRestorationMagic = ItemUpgradeClass(upgrade_id = 0x2102,  name = "of Major Restoration Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorCommuning = ItemUpgradeClass(upgrade_id = 0x2002,  name = "of Major Communing", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorSpawningPower = ItemUpgradeClass(upgrade_id = 0x2402,  name = "of Major Spawning Power", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorChannelingMagic = ItemUpgradeClass(upgrade_id = 0x2203,  name = "of Superior Channeling Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorRestorationMagic = ItemUpgradeClass(upgrade_id = 0x2103,  name = "of Superior Restoration Magic", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorCommuning = ItemUpgradeClass(upgrade_id = 0x2003,  name = "of Superior Communing", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorSpawningPower = ItemUpgradeClass(upgrade_id = 0x2403,  name = "of Superior Spawning Power", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorMysticism = ItemUpgradeClass(upgrade_id = 0x2C01,  name = "of Minor Mysticism", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorEarthPrayers = ItemUpgradeClass(upgrade_id = 0x2B01,  name = "of Minor Earth Prayers", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorScytheMastery = ItemUpgradeClass(upgrade_id = 0x2901,  name = "of Minor Scythe Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorWindPrayers = ItemUpgradeClass(upgrade_id = 0x2A01,  name = "of Minor Wind Prayers", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorMysticism = ItemUpgradeClass(upgrade_id = 0x2C02,  name = "of Major Mysticism", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorEarthPrayers = ItemUpgradeClass(upgrade_id = 0x2B02,  name = "of Major Earth Prayers", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorScytheMastery = ItemUpgradeClass(upgrade_id = 0x2902,  name = "of Major Scythe Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorWindPrayers = ItemUpgradeClass(upgrade_id = 0x2A02,  name = "of Major Wind Prayers", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorMysticism = ItemUpgradeClass(upgrade_id = 0x2C03,  name = "of Superior Mysticism", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorEarthPrayers = ItemUpgradeClass(upgrade_id = 0x2B03,  name = "of Superior Earth Prayers", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorScytheMastery = ItemUpgradeClass(upgrade_id = 0x2903,  name = "of Superior Scythe Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorWindPrayers = ItemUpgradeClass(upgrade_id = 0x2A03,  name = "of Superior Wind Prayers", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorLeadership = ItemUpgradeClass(upgrade_id = 0x2801,  name = "of Minor Leadership", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorMotivation = ItemUpgradeClass(upgrade_id = 0x2701,  name = "of Minor Motivation", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorCommand = ItemUpgradeClass(upgrade_id = 0x2601,  name = "of Minor Command", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMinorSpearMastery = ItemUpgradeClass(upgrade_id = 0x2501,  name = "of Minor Spear Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorLeadership = ItemUpgradeClass(upgrade_id = 0x2802,  name = "of Major Leadership", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorMotivation = ItemUpgradeClass(upgrade_id = 0x2702,  name = "of Major Motivation", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorCommand = ItemUpgradeClass(upgrade_id = 0x2602,  name = "of Major Command", upgrade_type = ItemUpgradeClassType.Suffix)
    OfMajorSpearMastery = ItemUpgradeClass(upgrade_id = 0x2502,  name = "of Major Spear Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorLeadership = ItemUpgradeClass(upgrade_id = 0x2803,  name = "of Superior Leadership", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorMotivation = ItemUpgradeClass(upgrade_id = 0x2703,  name = "of Superior Motivation", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorCommand = ItemUpgradeClass(upgrade_id = 0x2603,  name = "of Superior Command", upgrade_type = ItemUpgradeClassType.Suffix)
    OfSuperiorSpearMastery = ItemUpgradeClass(upgrade_id = 0x2503,  name = "of Superior Spear Mastery", upgrade_type = ItemUpgradeClassType.Suffix)
    
    UpgradeMinorRune_Warrior = ItemUpgradeClass(upgrade_id = 0x00B3,  name = "Upgrade warrior minor rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMinorRune_Warrior = ItemUpgradeClass(upgrade_id = 0x0167,  name = "Applies to warrior minor rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMajorRune_Warrior = ItemUpgradeClass(upgrade_id = 0x00B9,  name = "Upgrade warrior major rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMajorRune_Warrior = ItemUpgradeClass(upgrade_id = 0x0173,  name = "Applies to warrior major rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeSuperiorRune_Warrior = ItemUpgradeClass(upgrade_id = 0x00BF,  name = "Upgrade warrior superior rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToSuperiorRune_Warrior = ItemUpgradeClass(upgrade_id = 0x017F,  name = "Applies to warrior superior rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMinorRune_Ranger = ItemUpgradeClass(upgrade_id = 0x00B4,  name = "Upgrade ranger minor rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMinorRune_Ranger = ItemUpgradeClass(upgrade_id = 0x0169,  name = "Applies to ranger minor rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMajorRune_Ranger = ItemUpgradeClass(upgrade_id = 0x00BA,  name = "Upgrade ranger major rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMajorRune_Ranger = ItemUpgradeClass(upgrade_id = 0x0175,  name = "Applies to ranger major rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeSuperiorRune_Ranger = ItemUpgradeClass(upgrade_id = 0x00C0,  name = "Upgrade ranger superior rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToSuperiorRune_Ranger = ItemUpgradeClass(upgrade_id = 0x0181,  name = "Applies to ranger superior rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMinorRune_Monk = ItemUpgradeClass(upgrade_id = 0x00B2,  name = "Upgrade monk major rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMinorRune_Monk = ItemUpgradeClass(upgrade_id = 0x0165,  name = "Applies to monk minor rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMajorRune_Monk = ItemUpgradeClass(upgrade_id = 0x00B8,  name = "Upgrade monk major rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMajorRune_Monk = ItemUpgradeClass(upgrade_id = 0x0171,  name = "Applies to monk major rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeSuperiorRune_Monk = ItemUpgradeClass(upgrade_id = 0x00BE,  name = "Upgrade monk superior rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToSuperiorRune_Monk = ItemUpgradeClass(upgrade_id = 0x017D,  name = "Applies to monk superior rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMinorRune_Necromancer = ItemUpgradeClass(upgrade_id = 0x00B0,  name = "Upgrade necromancer minor rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMinorRune_Necromancer = ItemUpgradeClass(upgrade_id = 0x0161,  name = "Applies to necromancer minor rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMajorRune_Necromancer = ItemUpgradeClass(upgrade_id = 0x00B6,  name = "Upgrade necromancer major rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMajorRune_Necromancer = ItemUpgradeClass(upgrade_id = 0x016D,  name = "Applies to necromancer major rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeSuperiorRune_Necromancer = ItemUpgradeClass(upgrade_id = 0x00BC,  name = "Upgrade necromancer superior rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToSuperiorRune_Necromancer = ItemUpgradeClass(upgrade_id = 0x0179,  name = "Applies to necromancer superior rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMinorRune_Mesmer = ItemUpgradeClass(upgrade_id = 0x00AF,  name = "Upgrade mesmer minor rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMinorRune_Mesmer = ItemUpgradeClass(upgrade_id = 0x015F,  name = "Applies to mesmer minor rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMajorRune_Mesmer = ItemUpgradeClass(upgrade_id = 0x00B5,  name = "Upgrade mesmer major rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMajorRune_Mesmer = ItemUpgradeClass(upgrade_id = 0x016B,  name = "Applies to mesmer major rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeSuperiorRune_Mesmer = ItemUpgradeClass(upgrade_id = 0x00BB,  name = "Upgrade mesmer superior rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToSuperiorRune_Mesmer = ItemUpgradeClass(upgrade_id = 0x0177,  name = "Applies to mesmer superior rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMinorRune_Elementalist = ItemUpgradeClass(upgrade_id = 0x00B1,  name = "Upgrade elementalist minor rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMinorRune_Elementalist = ItemUpgradeClass(upgrade_id = 0x0163,  name = "Applies to elementalist minor rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMajorRune_Elementalist = ItemUpgradeClass(upgrade_id = 0x00B7,  name = "Upgrade elementalist major rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMajorRune_Elementalist = ItemUpgradeClass(upgrade_id = 0x016F,  name = "Applies to elementalist major rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeSuperiorRune_Elementalist = ItemUpgradeClass(upgrade_id = 0x00BD,  name = "Upgrade elementalist superior rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToSuperiorRune_Elementalist = ItemUpgradeClass(upgrade_id = 0x017B,  name = "Applies to elementalist superior rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMinorRune_Assassin = ItemUpgradeClass(upgrade_id = 0x013B,  name = "Upgrade assassin minor rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMinorRune_Assassin = ItemUpgradeClass(upgrade_id = 0x0277,  name = "Applies to assassin minor rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMajorRune_Assassin = ItemUpgradeClass(upgrade_id = 0x014C,  name = "Upgrade assassin major rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMajorRune_Assassin = ItemUpgradeClass(upgrade_id = 0x0279,  name = "Applies to assassin major rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeSuperiorRune_Assassin = ItemUpgradeClass(upgrade_id = 0x013D,  name = "Upgrade assassin superior rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToSuperiorRune_Assassin = ItemUpgradeClass(upgrade_id = 0x027B,  name = "Applies to assassin superior rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMinorRune_Ritualist = ItemUpgradeClass(upgrade_id = 0x013E,  name = "Upgrade ritualist minor rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMinorRune_Ritualist = ItemUpgradeClass(upgrade_id = 0x027D,  name = "Applies to ritualist minor rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMajorRune_Ritualist = ItemUpgradeClass(upgrade_id = 0x013F,  name = "Upgrade ritualist major rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMajorRune_Ritualist = ItemUpgradeClass(upgrade_id = 0x027F,  name = "Applies to ritualist major rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeSuperiorRune_Ritualist = ItemUpgradeClass(upgrade_id = 0x0140,  name = "Upgrade ritualist superior rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToSuperiorRune_Ritualist = ItemUpgradeClass(upgrade_id = 0x0281,  name = "Applies to ritualist superior rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMinorRune_Dervish = ItemUpgradeClass(upgrade_id = 0x0182,  name = "Upgrade dervish minor rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMinorRune_Dervish = ItemUpgradeClass(upgrade_id = 0x0305,  name = "Applies to dervish minor rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMajorRune_Dervish = ItemUpgradeClass(upgrade_id = 0x0183,  name = "Upgrade dervish major rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMajorRune_Dervish = ItemUpgradeClass(upgrade_id = 0x0307,  name = "Applies to dervish major rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeSuperiorRune_Dervish = ItemUpgradeClass(upgrade_id = 0x0184,  name = "Upgrade dervish superior rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToSuperiorRune_Dervish = ItemUpgradeClass(upgrade_id = 0x0309,  name = "Applies to dervish superior rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMinorRune_Paragon = ItemUpgradeClass(upgrade_id = 0x0185,  name = "Upgrade paragon minor rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMinorRune_Paragon = ItemUpgradeClass(upgrade_id = 0x030B,  name = "Applies to paragon minor rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeMajorRune_Paragon = ItemUpgradeClass(upgrade_id = 0x0186,  name = "Upgrade paragon major rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToMajorRune_Paragon = ItemUpgradeClass(upgrade_id = 0x030D,  name = "Applies to paragon major rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)
    UpgradeSuperiorRune_Paragon = ItemUpgradeClass(upgrade_id = 0x0187,  name = "Upgrade paragon superior rune", upgrade_type = ItemUpgradeClassType.UpgradeRune)
    AppliesToSuperiorRune_Paragon = ItemUpgradeClass(upgrade_id = 0x030F,  name = "Applies to paragon superior rune", upgrade_type = ItemUpgradeClassType.AppliesToRune)

ITEM_UPGRADES = [up.value for up in ItemUpgrade.__members__.values() if isinstance(up.value, ItemUpgradeClass)]  